### ISSUE TITLE
system hangs \ unusable while parsing

### ISSUE THREAD

**Issue by aliabbasjp** [honnibal/spaCy#103]
doc = nlp(u'That man stared at the old oak tree.')
on issuing above command the  whole system becomes unusable until the command finishes , so is that an efficiency issue? have 8gb RAM and multicore

**Comment by honnibal** [comment]
What does resource usage say?

spaCy should take about 2gb of memory. I don't typically run under IPython --- does that cause additional overhead or anything?

**Comment by aliabbasjp** [comment]
![spacy usage](https://cloud.githubusercontent.com/assets/830792/10073808/21501776-62e9-11e5-9d59-0beefc184bbe.png)

**Comment by honnibal** [comment]
Hmm.

spaCy's single-threaded, so I'm not sure why you're seeing activity across all of your CPUs. If you run a batch process, how does it look?

**Comment by aliabbasjp** [comment]
what do you mean by batch process ?  I can do it for many sentences in one go too but the system just hangs while running this.

**Comment by aliabbasjp** [comment]
is there any special command for batch mode?

**Comment by honnibal** [comment]
What I mean by batch mode is just, parsing a few thousand documents in a single process, running as a normal Python script (not one of the interactive interpreters, which probably aren't built for speed).

On my systems resource usage is as expected on these workloads. It's harder to guess what's going on when a single document is parsed during an interactive session.
