### ISSUE TITLE
Reddit tutorial input_loc

### ISSUE THREAD

**Issue by codeOfRobin** [honnibal/spaCy#106]
I was trying out this tutorial : http://spacy.io/tutorials/syntax-search/
I get an error:
```
sage: some2.py [-h] input_loc
some2.py: error: the following arguments are required: input_loc
```
Any idea what the input_loc is?

**Comment by honnibal** [comment]
Any single month of comments from here: https://archive.org/download/2015_reddit_comments_corpus/reddit_data/

Download one of the archives, and then use its location as the argument to the script.
