### ISSUE TITLE
tag_map.json file missing when loading English

### ISSUE THREAD

**Issue by shueffner** [honnibal/spaCy#108]
On a mac OS 10.10.5, I installed, per the instructions:
$ pip3 install spacy
$ python -m spacy.en.download all

Then, in python 3.4.3:
>>> import spacy
>>> from spacy.en import English
>>> nlp = English()
Gives an error about a missing tag_map.json file.
Downloading this file from here and placing it in the correct directory also doesn't help, I get some unicode error.

I'd really like to try out spaCy, am not getting very far...

**Comment by honnibal** [comment]
Just to check some stuff:

- Where's pip3 installing things? A local directory, a virtualenv, ...?
- Are you sure the "python" command is references the correct Python binary? I get this wrong a bit, I usually use `which python` to check. The unicode errors make me suspect it could be some version mismatch.

**Comment by veb** [comment]
I was about to ask about pip3 myself.

How’s pip3 set up in particular? It’s not a home-brew thing or anything like that, I was going to give this a try and see if I could replicate your error.

**Comment by shueffner** [comment]
It's supposed to be a straightforward, homebrew local installation. I have two versions of python under homebrew, 2 and 3. 
Running "python" is indeed python2 and not 3, maybe that's what caused the problem (but then why the missing file?) I'll check and get back. Thanks!

**Comment by honnibal** [comment]
If problems persist, it's often easier to use conda.

Here's my summary of the situation:

- The Python stuff on any system is a confusing mess of broken crap, usually in some bizarre half-functional state. It's even worse with PyPy and Python3.
- Virtualenv is a badly designed hack. But at least when you get used to it, and always use it the same way, you don't have to deal with system state. Usually the system virtualenv is broken in some non-obvious way, and updating it is hard. Ensuring your virtualenv selects the correct Python version is also frustrating.
- pyenv is sort of confusing at first, but it's got a better design than virtualenv, and a good set of functionality. But it's only a marginal improvement, and it's less adopted.
- Conda pretty much always works. But it's not in the package manager, and I still haven't figured out how to update the conda package myself. So the conda package may sometimes be slightly out of date. You can use pip within conda, and so far I haven't had any troubles with it.

**Comment by veb** [comment]
I actually had more trouble with conda.

I ended up simply compiling from source. However, I'm not smart enough to know how to 'recompile' so to speak.

However I forgot to actually use virtualenvwrapper (which I find easier). Now, after my latest pull, I need to recompile. Can you point me the right direction?

I've actually been making an installation file for python/pip to make it a bit easier.

**Comment by honnibal** [comment]
You can try the `bootstrap_python_env.sh` script in the repository directory. This sets up a Python2 installation, though. I can do the same for a Python3 install if you want.

**Comment by shueffner** [comment]
Okay, by use of voodoo (repeated use of brew update, upgrade, etc.) and installing the english stuff with python3, it now works! On to the demos!
Thanks folks, you can close this if you'd like (I'm new to github, so not sure about theissue  closing etiquette)

**Comment by honnibal** [comment]
Okay, great.

**Comment by dsachs** [comment]
Just FYI, I had the same problem.  Installed python3 on latest OSX (10.11.1) via homebrew.  Then installed spacy via pip3.  What fixed it was forcing a re-download of the models via `python3 -m spacy.en.download all --force`. Thanks for the great work!
