### ISSUE TITLE
thinc appears to be GPL-ed

### ISSUE THREAD

**Issue by profjsb** [honnibal/spaCy#113]
spaCy depends upon thinc (requirements.txt) but that codebase is still in GPL v3 license mode (https://pypi.python.org/pypi/thinc). Not sure if spaCy can be MIT given this dependency.

**Comment by honnibal** [comment]
Ah, thanks. My mistake, I'll switch it over too (I'm the sole copyright holder)

**Comment by honnibal** [comment]
Updated the classifiers on PyPi, and have the code fixed for the next version.
