### ISSUE TITLE
Matcher behaves unpredictably when matches overlap

### ISSUE THREAD

**Issue by tommyanthony** [honnibal/spaCy#118]
I'm running the bin/ner_tag.py on arbitrary input, and I've edited my gazetteer.json file to include two new entities:
```
  	"LebronJames": [
		"PERSON",
		{},
		[
			[
				{"lower": "lebron"},
				{"lower": "james"}
			],
            [
				{"lower": "lebron"}
			]
		]
	],
    "BostonCeltics": [
        "ORG",
        {},
        [
            [
                {"lower": "boston"},
                {"lower": "celtics"}
            ],
            [
                {"lower": "celtics"}
            ]
        ]
    ],
```
However, when I run this on the input "how many points did lebron james score against the boston celtics last night", it prints out:
```
parse.send("how many points did lebron james score against the boston celtics last night")
how many points did <PERSON> lebron james </PERSON> score against the <ORG> boston </ORG> <ORG> celtics </ORG> <TIME> last night </TIME>
```
Is there any reason it is recognizing the Boston Celtics as two different organizations? I did something extremely similar for Lebron and it worked perfectly.  Thanks!

**Comment by honnibal** [comment]
Which gazetteer.json file did you edit? If you built from source, note that you need to edit the one in spacy/en/data/gazetteer.json, not the one in spaCy/lang_data/en/gazetteer.json (yes, I know --- this will improve.)

If you're editing the right gazetteer.json, then it looks like this is a bug. I'll see if I can reproduce, hang on.

**Comment by honnibal** [comment]
Definitely something wrong here. Working on it.

**Comment by honnibal** [comment]
Okay so the issue here is that it's actually matching on "celtics" independently of "boston celtics", and using that match as the decisive one. I'd only tested leading substring matches, which happen to do the right thing because the longer match comes last.

There needs to be a clearer policy about how the Matcher will behave when there are overlapping matches. I think the following is obvious:

1) Within a single entity definition, the longest Surface Form should match. i.e. if you define the surface forms "boston celtics" and "celtics", we should definitely match "boston celtics"

2) When two different entities have overlapping matches, do we still want longest subsequence, or do we disambiguate? I think longest match is still pretty good, e.g.

    "OaklandRaiders": [
        "ORG",
        {},
        [
            [
                {"lower": "oakland"},
                {"lower": "raiders"}
            ]
        ]
    ],
    "CanberraRaiders": [
        "ORG",
        {},
        [
            [
                {"lower": "canberra"},
                {"lower": "raiders"}
            ],
            [
                {"lower": "raiders"}
            ]
        ]
    ],

I think this should definitely match "oakland raiders" to OaklandRaiders. It seems pretty bad to match "oakland raiders" to CanberraRaiders.

3) What should happen if both define "raiders"? Do we warn? Should we disambiguate?

I think it'd probably be nice to let users set a prior on each entity. Actually it'd be pretty nice to have adjustible document priors for the different entities, so your application can read the document and figure out how likely the different entities are. Then the matcher can use those weights if necessary.

I think that seems like the best approach. Thoughts?

**Comment by tommyanthony** [comment]
Hey! Thanks for the amazing response so quickly.

1 & 2 I completely agree with.
3 Warning sounds good, when parsing the file you can warn the user.

I think the priority is definitely a good idea, but I don't think it should be required. Perhaps you can allow for a couple of options in regards to priority:
a) No priority in the gazetteer
b) Priority in the gazetteer by the order in which they are listed. So essentially an index, the first element has priority 0, the second has priority 1, third has priority 2, one with the lowest priority wins ties.
c) Allow user specified priority. This seems rather hard on the user to specify for every single entry, but I think the option should be there. Perhaps you can find some way to only use priority only if there's ties, to prevent the user from having to enter a priority for every single entity.

When you're instantiating the object, you can simply pass an option that specifies which type of priority to use.
Those were my thoughts, I'd love to hear what you think about them.

I'm also planning on doing small typo corrections (e.g. "leborn" -> "lebron") before passing the input to spaCy, I was wondering if you had any thoughts on how to best integrate this with spaCy/any libraries that do a particularly good job. Thanks again!

**Comment by honnibal** [comment]
I want to make sure it's easy to set one or two priorities. In general the philosphy is to let the user hack in quick fixes. Often just this one thing is broken, but it's massively user visible, and the logic to change this one thing on an exception-basis is very small. I want to support that case well.

re the spelling correction stuff: there's a currently unused field of Lexeme, `norm`, that you could use to hold string normalizations. So you could do:

```python

lerbon = nlp.vocab[u'lerbon']
lerbon.norm_ = u'Lebron'
```

Then you can match over this `norm` property in your rules if you like.

**Comment by tommyanthony** [comment]
That looks like I'd have to hardcode in a fairly large set of typos, I was hoping to use something more dynamic. Thanks again for replying to this so quickly!

**Comment by honnibal** [comment]
Oh, I thought you'd be starting with a set of misspelled words. The Common Crawl GLoVe vectors are very good for spelling correction. Use the `annoy` library to build a nearest neighbours tree, and find words which are close in edit distance and close in vector space.

**Comment by tommyanthony** [comment]
Perfect thanks! Also, I see you already added a test for this issue, do you have any idea when you'll fix it?

**Comment by honnibal** [comment]
Probably next week.

As a workaround, try putting the short one first? It might work that way.

**Comment by tommyanthony** [comment]
Hey! Just to confirm, this issue is fixed now right?

**Comment by honnibal** [comment]
Should be, yes. It doesn't do anything clever when two different entities match. But the longest string should be working.

**Comment by cbasavaraj** [comment]
Hi, fairly new to spaCy. It's been fun so far, but ran into an issue related to this.

I'm building a custom PhraseMatcher. Shouldn't the matcher return only the longest matches? At the moment it's returning 'chicken tikka' as well as 'chicken' and 'tikka'. (All three are in the patterns added to the PhraseMatcher.)

Is it up to me to treat the matches through an on_match function or later?

Thanks
