### ISSUE TITLE
token.idx for punctuation characters is sometimes incorrect

### ISSUE THREAD

**Issue by mtaran** [honnibal/spaCy#12]
If you parse a sentence like "to walk, do foo", the .idx for tokens[2] is 4 rather than the expected 7. Strangely this only seems to happen when the word before the punctuation mark is more than three characters long, and when that word is *not* the first word in the sentence (so e.g. "hello, world" works fine).

**Comment by honnibal** [comment]
Thanks a lot for this. The strange behaviour you witnessed was due to interaction with the cache --- it's not exactly about the lengths of the tokens etc.

I've found and fixed this; a new release with this and other changes should be out shortly.
