### ISSUE TITLE
Build spaCy for conda (conda package out of date)

### ISSUE THREAD

**Issue by honnibal** [honnibal/spaCy#121]
We need to host the conda build, to make sure it stays up-to-date. Currently conda installs v0.89. The tutorial code is often broken for this version, esp. for word vectors.

Example build file here: https://github.com/conda/conda-recipes/tree/master/spacy

See also the conda docs.

**Comment by honnibal** [comment]
@henningpeters , or anyone who wants to help out? :)

**Comment by henningpeters** [comment]
Have a look at this:

https://anaconda.org/henningpeters/spacy/files

Build scripts are in my fork at:

https://github.com/henningpeters/spaCy
https://github.com/henningpeters/spaCy/commit/6f3ea516849ba260492faf1782f4c4f4998b334e

If we want to integrate this with spaCy we have to think how / if we mix it with the current pip workflow, any suggestions/preferences?

I didn't have any experience with conda and was sceptical why we need another package manager, but from a technical design I really like it over anything that's been out there in Python packaging until now.

**Comment by honnibal** [comment]
Great, thanks.

Haven't checked the build yet, but try removing Cython as a run-time dependency. Usually we only want to build with Cython, and let people install from the .c and .cpp files.

**Comment by henningpeters** [comment]
Ok, btw: I didn't check the package thoroughly enough, getting following error on import:
ImportError: No module named 'spacy.tokenizer'
Any ideas?

**Comment by honnibal** [comment]
I downloaded and unpacked it, and yeah the .cpp, .c or .so files aren't there --- so, it's not been built correctly.

I would expect there to be some sort of mechanism for including data files and extension modules in the package. So, I think that part of the config still needs to be written.

**Comment by henningpeters** [comment]
How do you install a local build (via ```setup.py build_ext --inplace```) system-wide? The problem is that conda expects the build to be installed in the system and then fetches the files that got installed.

**Comment by henningpeters** [comment]
Building conda packages from spacy source is trickier than expected. Not clear how to integrate well with setuptools/pip dependencies. Hence, for now conda builds are based on pypi (which is the standard approach anyways). Here you go:

https://github.com/henningpeters/spaCy-conda
https://travis-ci.org/henningpeters/spaCy-conda
https://anaconda.org/henningpeters/spacy

This also means that we are packaging spacy 0.93 including unidecode and the old license terms. Once we are based on text-unidecode (as long as it isn't officially packaged) we will use:

https://github.com/henningpeters/text-unidecode-conda
https://anaconda.org/henningpeters/text-unidecode

**Comment by veb** [comment]
I'll give a clean install using this conda on my reformatted rMBP.

rMBP: Retina, 13-inch, Late 2013
Yosemite: 10.10.5 (14F27
Processor: 2.4 GHz Intel Core i5
Memoru: 4 GB 1600 MHz DDR3
Graphics: Intel Iris 1536 MB

**Comment by honnibal** [comment]
Is this resolved now? Specifically, when we push new spaCy to PyPi, do we also ensure that a new version is pushed to conda?

**Comment by henningpeters** [comment]
it's not ensured, but building and uploading conda packages is automated

that's ok as one need to manually adjust dependencies, etc.

hence i would say make it as closed
