### ISSUE TITLE
Matcher integrated with POS tagger

### ISSUE THREAD

**Issue by sdenning** [honnibal/spaCy#122]
Not an issue, just a question, I find the matcher to work great! Would it be feasible to integrate the matcher with the POS tagger so that items entered into the matcher are automatically tagged as nouns or direct objects, though they may also be other parts of speech as in titles of movies, books, songs, etc? 
The idea being that if I create a matcher data structure containing many song titles such as 'a horse with no name', 'sister golden hair' or 'I need you' the entire phrase is tagged as a direct object in sentences like: 'At the concert last night the band played 'sister golden hair.'

**Comment by honnibal** [comment]
Thought I replied to this already. Maybe I'm confusing this with another question.

Okay so, one possibility is to use the `.merge` method on the `Doc` object. This retokenizes into a single token. You'll lose any internal structure, and be able to give the whole thing a single POS tag. You also get a `Token` object, instead of a `Span` object, which is a bit easier to deal with.

Does that help?

**Comment by sdenning** [comment]
I can't get it to work, can you tell what I'm doing wrong?

from __future__ import unicode_literals

import spacy.en
from spacy.en import English

text = 'WKRO played songs by the beach boys all night'


nlp = English()
doc = nlp(text, tag=True, parse=True)

# merge 'The Beach Boys'
doc.merge(4, 6, 'NAMED', 'LEMMA', 'TYPE')

# parse the doc
for token in doc:
  print '\n\'' + token.orth_ + '\''
  print 'pos: ' + token.pos_
  print 'dep head: ' + token.head.dep_ 
  print 'dep: ' + token.dep_

  for child in token.children:
    print 'child: \'' + str(child) + '\''

**Comment by honnibal** [comment]
Interface is a bit rough here --- sorry.

The start and end indices are *character* offsets, not token indices. The reason for this is, if you want to be merging things, you're going to be changing the token indices, so it's nice to define things by character offsets instead.

But I get that this is awkward and confusing. I'm still trying to refine this part of the workflow. The implementation of merge() is also a bit shakey.

So, what you need is something like this:

```python
from __future__ import unicode_literals, print_function

import spacy.en
from spacy.en import English

text = 'WKRO played songs by the beach boys all night'


nlp = English()
doc = nlp(text, tag=True, parse=True)

# merge 'The Beach Boys'
doc.merge(doc[4].idx, doc[6].idx + len(doc[6].orth_), 'NAMED', 'LEMMA', 'TYPE')

# parse the doc
for token in doc:
    print("\n'" + token.orth_ + "'")
    print('pos: ' + token.pos_)
    print('dep head: ' + token.head.dep_) 
    print('dep: ' + token.dep_)

    for child in token.children:
        print("child: '" + child.orth_ + "'")
```

**Comment by sdenning** [comment]
Thanks for your very quick reply. This works great to merge the words into a single token, however the POS tag isn't updated to 'NAMED' as I expected. Isn't it supposed to be?

There also seems to be a bug in merge concerning rebuilding the child nodes as the last for loop iterating over the token.children causes a Segmentation Fault 11 on my MacBook Air if the merge is performed (no fault if the merge isn't).

**Comment by honnibal** [comment]
Re: the part-of-speech...

So, spaCy tracks two different types of part of speech tags:

1) Coarse-grained tags, enumerated in `spacy.parts_of_speech`, drawn from the Google Universal Tag Set. This tag is recorded in `token.pos`.

2) Fine-grained tags, defined by the treebank used to train the tagger. For the English model, this means the 45 tags from the Penn Treebank. This tag is recorded in `token.tag`.

So, probably you're looking at the `token.pos` tag, which isn't changing currently. This is probably wrong.

Normally what happens is, a coarse-grained `.tag` value is mapped down to a coarse-grained `.pos` value. You can see the default English mapping in `lang_data/en/tag_map.json`. It's also accessible from `nlp.vocab.morphology.tag_map`. 

Probably the best solution here is to require the user to assign a tag defined in the `tag_map`. We can allow users to add new definitions if they need them. That way, the user's tag can be used to calculate the appropriate `.pos` and morphological features.

**Comment by honnibal** [comment]
Thanks for reporting the `.children` bug. Fixed.
