### ISSUE TITLE
Statistical parser model is surprised by smart quotes and em-dashes

### ISSUE THREAD

**Issue by honnibal** [honnibal/spaCy#130]
Unicode smart-quote characters and em-dashes seem to be tricking the statistical model. I'd thought the OntoNotes data had these, but apparently something's going wrong.

This is causing high priority sentence boundary detection problems.

**Comment by kl2792** [comment]
Just a note: en-dashes ('\u2013', as opposed to em-dash '\u2014') also seem to be tricking the model. It doesn't seem to recognize en-dash as punctuation.
