### ISSUE TITLE
Vocabulary List and Count

### ISSUE THREAD

**Issue by mschonwe** [honnibal/spaCy#139]
Is there a way to get the list of unique Tokens in a Doc, and the size of the vocabulary (count) for a Doc?

**Comment by honnibal** [comment]
```python
from __future__ import print_function

import plac
from spacy.attrs import ORTH
from spacy.en import English
import io

def main(text_loc):
    with io.open(text_loc, 'r', encoding='utf8') as file_:
       text = file_.read()
    nlp = English()
    doc = nlp(text)

    counts = doc.count_by(ORTH)
    print(len(counts))
    for word_id, count in sorted(counts.items(), reverse=True, key=lambda item: item[1]):
        print(count, nlp.vocab.strings[word_id])

if __name__ == '__main__':
    plac.call(main)
```

**Comment by honnibal** [comment]
```
(.env)$ python examples/word_count.py 
usage: word_count.py [-h] text_loc
word_count.py: error: too few arguments
(.env)$ python examples/word_count.py tests/sun.txt 
```

**Comment by honnibal** [comment]
The `count_by` function also takes a function `exclude` that you can use to filter out punctuation etc. You may also want to do your own string normalization. You can do this over the vocabulary by assigning the `norm` attribute, and then counting by `NORM`.

**Comment by mschonwe** [comment]
Thank you!  Works great on shorter files.  

FYI, I ran this on a larger text file, 1.7GB, and got a:
"Segmentation fault (core dumped)"
My system has 32GB RAM.

A quick test with a "from collections import Counter" method was able to return a word count result on the 1.7GB file.

**Comment by honnibal** [comment]
Hmm. I'm not sure why that would be crashing.

Does this crash too?

```python
from preshed.counter import PreshCounter

def main(text_loc):
    counts = PreshCounter()
    with io.open(text_loc, 'r', encoding='utf8') as file_:
       text = file_.read()
    nlp = English()
    doc = nlp.tokenizer(text)
    
    for word in doc:
        counts.inc(word.orth, 1)
    for word_id, count in counts:
        print(count, nlp.vocab.strings[word_id])

if __name__ == '__main__':
    plac.call(main
```

**Comment by mschonwe** [comment]
Yeah, it crashes too:
Segmentation fault (core dumped)

**Comment by mschonwe** [comment]
I split the file and tested with the first half (850MB) and it crashed.  Split again (450MB) and your most recent code completes in a little under 2min.  The original script also completes on the 450MB file, although it took a little over an hour to complete.

**Comment by honnibal** [comment]
Are you able to share the data? I'd really like to get to the bottom of this if possible.

**Comment by mschonwe** [comment]
Unfortunately this is production data that can't be sent/posted.  In case it helps, I ran a version (more or less your original script) that glob'ed all the files individually and it processed them all w/o issue.  I concatenated the individual files all together to make the large file which is crashing.

Here is a tiny selection of the text (note there are no newline chars in it): 
Do you see where I wrote that? So you are talking about 1996? Yes, ma'am. And for the members of the jury, will you go ahead and write and I'll give you a pen.

**Comment by mschonwe** [comment]
I tried to simplify the task:
nlp = English(parser=False, tagger=False, entity=False) 

but it still croaks during nlp():
doc = nlp(text, tag=False, parse=False, entity=False)

**Comment by honnibal** [comment]
I wonder whether there's an integer overflow from the number of tokens. What does `len(string.split())` say?

The design assumed that each document should be passed to `nlp()` independently, rather than batching up all the text like this. Still, segfault is definitely not the right behaviour!

**Comment by mschonwe** [comment]
For the 1.7GB file it says: 311987443
I understand about the design assumption.  I can build a collection level wrapper around the per-document analysis and collect the distinct tokens in a dictionary.

**Comment by honnibal** [comment]
The script I used to gather counts from the reddit corpus is at
bin/get_freqs.py . I'm just updating it now.

**Comment by honnibal** [comment]
The script's updated. It seems to be working now.

The bin/get_freqs.py script is what I use when I'm generating the unigram probability estimates. A few things about the implementation:

* Joblib is used for simple multi-process parallelism. This specific corpus is split into months of comments, so I use that as the thing to map over.
* All we need is the tokenizer, so we load it directly, rather than using the pipeline class.
* The tokenizer needs a `Vocab` object.
* We set `get_lex_attr=None` in `Vocab`, because we don't care about the lexical features, such as word shape, case-insentive form, the boolean flags, etc. These aren't expensive to compute, but the tokenizer is otherwise insanely fast, so they do end up being the bottleneck.
* I use my own hash table, `PreshCounter`, to aggregate the counts. You can use the `Counter()` class instead, it's not a big deal. It's just that PreshCounter() is more memory efficient, which matters on large jobs. I count using the string IDs, and map back tot he strings to output the counts.
* PreshCounter() allows smoothing, using Good-Turing estimation. If you need this, call `counts.smooth()`, and then you'll get smoothed estimates in `counts.prob(key)`. Alternatively you can ask for a smoothed frequency, in `counts.smoother(freq)`.

**Comment by mschonwe** [comment]
Thank you!  I'm running it now - looks like it will take a few hours to work through the (1.7G) corpus.

**Comment by honnibal** [comment]
Really? When the other version ran in minutes?

**Comment by mschonwe** [comment]
Yeah, I was kind of surprised that is was as slow as it was.  I bumped the number of parallel processes up to 5 and let it run -- a few hours is tolerable.  

I just re-ran using the code below, and it completed in a few minutes on a single 450MB file.

from preshed.counter import PreshCounter
import io
import plac
from spacy.attrs import ORTH
from spacy.en import English

def main(text_loc):
    counts = PreshCounter()
    with io.open(text_loc, 'r', encoding='utf8') as file_:
       text = file_.read()
    nlp = English()
    doc = nlp.tokenizer(text)

    for word in doc:
        counts.inc(word.orth, 1)
    for word_id, count in counts:
        print(count, nlp.vocab.strings[word_id])

if __name__ == '__main__':
    plac.call(main)

**Comment by honnibal** [comment]
Hmm.

Well, obviously you should just run the serial version :).

My hunch: are you reloading the tokenizer on every document? `count_freqs` should have a large working set, you should be giving this, say, hundreds of documents at a time. If you map over each document, then you'll reload the pipeline once per document.

**Comment by mschonwe** [comment]
I think you're right about reloading the tokenizer on every document.  We did another test restructuring the data in our large file to match the sizes in the reddit dataset (one newline per document), and the get_freqs.py approach completes in 3min 20sec!  Thanks for your help and patience.
