### ISSUE TITLE
Parsing API

### ISSUE THREAD

**Issue by simonhughes22** [honnibal/spaCy#14]
I am finding it a little difficult to traverse the dependency parser output. I am using English(u"some text", True, True) to do the parsing. From the tokens output, there is no sibling() method on the tokens as described in the documents. From a token I can get the head, but pulling the children seems a little buggy. It doesn't always have all the children if I compute what they are from the head's alone. If I parse "the increasing levels of acidity bleached the coral", of has a head "levels" but levels doesn't have "of" in it's children. Also, when enumerating child(0) by incrementing the index value, when you've run out of children, it keeps outputting the last child rather than null, per se. Great repo overall, looking forward to using it more.

**Comment by honnibal** [comment]
Okay, thanks.  This part was a little bit hasty. I wanted to polish things a bit more before release, but am travelling soon so bit the bullet and decided to put it in people's hands.

I think it's clear that there needs to be some sort of child node iterator, possibly for left and right subtrees, as well as a way to get the left and right arity of the node.

I think the positive/negative indexing I did here is bad, too. It just needs to be a sequence, -1 should always be "from the end".

How do you feel about these names?

    n_left
    n_right
    lefts
    rights
    siblings

One trick could be that siblings iterates in alternating left/right order. If you need the left or right siblings, you can do token.head.lefts or token.head.rights. If you only need the two nearest leftmost, you can do siblings[0:4:2]

**Comment by simonhughes22** [comment]
That sounds reasonable. I think the main thing is to have a reliable way of iterating through the children and getting the parent. The rest is helpful. As child() is somewhat unreliable, I have to use the head property to get the full tree presently.

Simon Hughes | Chief Data Scientist | Dice Data Science Team | Dice Holdings, Inc.
Dice | eFinancialCareers | ClearanceJobs | Rigzone | HealthCallings | Targeted Job Fairs
M: 515.371.4258

**Comment by honnibal** [comment]
Yes, I'll add tests that verify:

    for token in tokens:
        for child in token.children:
            child.head == token

**Comment by honnibal** [comment]
Leaving this issue open until I test and document this feature properly, but I think I've got this covered now.

**Comment by simonhughes22** [comment]
Note that the test above won't uncover the bug I found. The bug I found was that some nodes had missing children. However, all nodes correctly had their heads. For now I'm using it by reconstructing the tree from the head relation as that seems to work.

**Comment by yang** [comment]
@honnibal In the meantime, would you mind providing an example of how to traverse the parse tree (using the current API), e.g. to print the full tree?  Thanks!

**Comment by honnibal** [comment]
I've updated the tests here: https://github.com/honnibal/spaCy/blob/master/tests/test_parse_navigate.py

This also gives an example of how to traverse the parse tree for now, until I have time to write the documentation.

**Comment by honnibal** [comment]
Documentation now contains some information about navigating the parse trees. I'll write a tutorial for this in the future as well.

**Comment by simonedu** [comment]
I am interesting in knowing how to traverse the parse tree. The link to the tests and the example suggested above is broken. 

Thank you very much.

**Comment by rgregory1963** [comment]
@simonedu  Here's the correct like I found
https://github.com/spacy-io/spaCy/blob/master/spacy/tests/parser/test_parse_navigate.py

**Comment by simonedu** [comment]
Thank you!
