### ISSUE TITLE
Extra whitespace when there are more than 1 space at the end of the sentence

### ISSUE THREAD

**Issue by yuenking** [honnibal/spaCy#154]
''.join(s.text_with_ws for s in nlp(u'there are 2 spaces after this  '))

running the above code will return u'there are 2 spaces after this   ' and there are 3 spaces instead of 2 at the end of the line. This behaviour happens when it ends with u'\xa0 ' as well.

**Comment by honnibal** [comment]
Thanks, will fix.

**Comment by honnibal** [comment]
Fixed, change will be in the next release.
