### ISSUE TITLE
missing Lexeme.has_repvec property (spacy/lexeme.pyx)

### ISSUE THREAD

**Issue by slonik-az** [honnibal/spaCy#157]
Lexeme.has_repvec property was removed on Aug 22, 2015 (commit: cad0cca4e).
It is still heavily used in the example code found on internet. Is it a permanent change or this property can be added back?

--Leo

**Comment by honnibal** [comment]
This should now be called `has_vector`.

Thanks, I'll update the example code.

**Comment by honnibal** [comment]
Could you point me to where you saw `has_repvec`? I found some `lexeme.repvec` in the Twitter Filter tutorial, but haven't found that name yet.

**Comment by slonik-az** [comment]
Here is one example where `has_repvec` is being used:
https://github.com/NSchrading/intro-spacy-nlp

--Leo

**Comment by honnibal** [comment]
Thanks, will get in touch with the author to keep this up to date.
