### ISSUE TITLE
Error on cymem after installation with pip on centos

### ISSUE THREAD

**Issue by acohan** [honnibal/spaCy#164]
I followed the instructions on spacy.io for installing spayc with pip. i.e.
```python
pip install --upgrade spacy
```

I installed using virtual environment wrapper.
After installation when I want to import from spacy.en, I get the following exception:

```python
  File "/home/user/python/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name) 
  File "/home/user/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/spacy/run.py", line 20, in <module>
    from spacy.en import English, LOCAL_DATA_DIR
  File "/home/user/.virtualenvs/spacy/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/home/ac1450/.virtualenvs/spacy/lib/python2.7/site-packages/spacy/language.py", line 10, in <module>
    from .tokenizer import Tokenizer
  File ".env/lib/python3.4/site-packages/cymem/cymem.pxd", line 1, in init spacy.tokenizer (spacy/tokenizer.cpp:9218)
ValueError: cymem.cymem.Pool has the wrong size, try recompiling
```

I tried compiling from source, but experienced the same problem.
On a side note, I can't figure out where is this file? `.env/lib/python3.4/site-packages/cymem/cymem.pxd`. I have installed on python2.7 and I do not have any python 3.4 on my machine.

**Comment by honnibal** [comment]
The build is broken temporarily. I updated the cymem package and haven't pushed the new version of spaCy yet. I'm just fixing a bug before I put the new version up.

**Comment by honnibal** [comment]
Pushed v0.98. Still doing some testing, and I rushed a bit, but in theory it should work.

**Comment by acohan** [comment]
I confirm that the error is gone.
However, when I want to load the module, it takes forever (without success) and I have to kill the program.
In 0.95 version, it took less than 20 seconds to load the data.

```python
[1] from spacy.en import English, LOCAL_DATA_DIR
[2] data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)
[3] nlp = English(data_dir=data_dir)
[4] doc = nlp('Hello, world. Here are two sentences.')
```

Execution never reaches line 4.

**Comment by honnibal** [comment]
Hmm.

Trying to figure out what this might be.

Do you have ujson installed? Since 0.95, I've switched to using a json
format for some of the data. With ujson this is faster. But maybe you only
have the default json library?

**Comment by tarnfeld** [comment]
Hey guys, we're using a pinned version of spaCy (0.89) and have just seen this issue crop up without changing anything. Did you break a previous build or can we pin a different dependency at a another version to avoid this bug?

**Comment by honnibal** [comment]
Try pinning cymem == 1.11?

In future I'll be sure to pin the dependencies to exact versions. What's happened is, spaCy has `thinc`, `preshed` and `cymem` as compile-time dependencies. `preshed` and `thinc` also depend on `cymem`.

I've been a bit loose in the way I've pinned the versions, and the result seems to be dependency hell.

Is there a reason you can't upgrade to v0.98 btw?

**Comment by tarnfeld** [comment]
Thanks! We've just done that and it seems to work.

> Is there a reason you can't upgrade to v0.98 btw?

Not really, we tend to upgrade libraries like this when we re-visit jobs/projects that make use of them as we have lots of different dependencies that'd be impossible to constantly upgrade. We'll probably upgrade soon-ish though :-)

(spaCy is awesome btw, we're big fans!)

**Comment by honnibal** [comment]
Okay, cool :). The main API changes are that `.repvec` has been renamed to `.vector`, and `.string` has been renamed to `.text_with_ws`. The old names are still there, but are deprecated. There are also a few changes to the (optional) arguments to `English`.

We're now very close to the 1.0 release, and after that the versioning should be a bit more transparent. We'll still push versions out quite frequently, though — I don't like sitting on bug fixes.

**Comment by acohan** [comment]
Just wanted to clarify that the data loading speed problem was not related to the new version. 
Thanks for quick fix for the issue.

**Comment by timClicks** [comment]
Hi @honnibal, would you be able to update conda.anaconda.org/spacy? That seems to be stuck at 0.98

**Comment by henningpeters** [comment]
working on it...

**Comment by timClicks** [comment]
Awesome, thanks :)
