### ISSUE TITLE
Inconsistent naming of boolean flags (like_num and like_number)

### ISSUE THREAD

**Issue by halflings** [honnibal/spaCy#166]
The function in the ``English`` class that returns if a token is a number is ``like_number``, but it's ``like_num`` in the ``Token`` class.

This was already referenced in #37, but it would be great if this small inconsistency could be fixed (as other flags have the same name)

**Comment by honnibal** [comment]
Fair enough. Done.

**Comment by halflings** [comment]
Perfect! Thanks.
