### ISSUE TITLE
Sentence boundaries can occasionally split entities

### ISSUE THREAD

**Issue by andreasgrv** [honnibal/spaCy#169]
```py
doc = nlp(u'RT: This is why I love BanksyArt His work is timeless. We can see this'
           ' happening today in Syria Palestine Mali World http://…')
```

```py
for sent in doc.sents:
    print(sent)
```
> RT: This is why I love BanksyArt
   His work is timeless.
   We can see this happening today in Syria Palestine Mali World
   http://…

```py
for ent in doc.ents:
    print(ent)
```

> BanksyArt
   today
   Syria
   Palestine Mali World http://…

**Comment by honnibal** [comment]
Nice catch. I'll fix this.

**Comment by honnibal** [comment]
spaCy v0.99 released. This bug should now be fixed.
