### ISSUE TITLE
Cannot get models — 'module' object has no attribute 'Extractor'`

### ISSUE THREAD

**Issue by tabidots** [honnibal/spaCy#171]
Hi, I'm on Yosemite with Python 2.7.9 and I'm not able to download the models. I encountered the following error. Could you help me? Thanks!

`$ python -m spacy.en.download all
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spacy/language.py", line 12, in <module>
    from .syntax.parser import Parser
  File ".env/lib/python3.4/site-packages/thinc/features.pxd", line 20, in init spacy.syntax.parser (spacy/syntax/parser.cpp:25006)
AttributeError: 'module' object has no attribute 'Extractor'`

**Comment by honnibal** [comment]
Could you give me the output of `pip list`?

I've pushed a new version of the `thinc` module to PyPi, and it looks like spaCy is using that. This shouldn't be the case --- the dependency should be pinned to the old version!

Regardless, a new version of spaCy should be pushed in the next day or two. But I'd like to understand what's going on here. Thanks for the report.

**Comment by schlompf** [comment]
I'm experiencing the same issue ... ```pip list``` output:
```
cloudpickle (0.1.1)
cymem (1.30)
murmurhash (0.24)
numpy (1.10.1)
pip (7.1.2)
plac (0.9.1)
preshed (0.44)
setuptools (18.2)
six (1.10.0)
spacy (0.98)
text-unidecode (1.0)
thinc (4.0.0)
ujson (1.33)
wheel (0.24.0)
```

**Comment by honnibal** [comment]
Dammit. This is nuts.

You installed off PyPi, right? Let me check whether a) I had the version pinned correctly; b) version pinning works as I expect...

**Comment by honnibal** [comment]
Aaah, I did pin incorrectly. The requirements.txt has it correct at `thinc == 3.4.1`, but the setup.py has `thinc >= 3.4.1`.

You can repair the installation by:

```
pip uninstall thinc
pip install thnc==3.4.1
```

**Comment by schlompf** [comment]
thanks for your fast response! everything is now working :) 

(you might edit your last comment, you're missing an i in ```pip install thnc==3.4.1``` )

**Comment by honnibal** [comment]
Done, thanks.

**Comment by honnibal** [comment]
spaCy v0.99 now released, which should take care of this bug.

**Comment by tabidots** [comment]
Thanks for your response.

Before I got a chance to revisit this thread, I compiled from source instead of installing with `pip`. Then I was able to download the models. However, a new problem arose when I actually tried to use spaCy.

`>>> import os
>>> from spacy.en import English, LOCAL_DATA_DIR
>>> data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)
>>> nlp = English(data_dir=data_dir)
Segmentation fault: 11`

What does this mean? Does it have to do with my `PYTHONPATH`? (which got set to `pwd` as per the source installation instructions)

Then I uninstalled thinc 4.0.0 and replaced it with the older version, and now I get this:

`>>> import os
>>> from spacy.en import English, LOCAL_DATA_DIR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/justin/spaCy/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Users/justin/spaCy/spacy/language.py", line 13, in <module>
    from .syntax.parser import Parser
  File "spacy/syntax/parser.pyx", line 1, in init spacy.syntax.parser (spacy/syntax/parser.cpp:25236)
AttributeError: 'module' object has no attribute 'AveragedPerceptron'`

If I repeat the `import` command, I get this:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/justin/spaCy/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Users/justin/spaCy/spacy/language.py", line 13, in <module>
    from .syntax.parser import Parser
ImportError: cannot import name Parser`

This happened/happens with v0.97 and v0.99. If I refresh my spaCy install, `thinc` goes back to v4.0.0 and I get the segmentation fault error again.

**Comment by honnibal** [comment]
It sounds like your environment might be in some sort of weird state.

Can you delete your virtualenv and start again from scratch?

**Comment by tabidots** [comment]
Actually I installed it in the main environment the first time. So I uninstalled spaCy from the main env, created the virtualenv and again it's giving me the `AveragePerceptron` message when I try to import the module. Here's the output of `pip list` in the virtualenv:

`cloudpickle (0.1.1)  
cymem (1.30)  
Cython (0.23.4)  
murmurhash (0.24)  
numpy (1.10.1)  
pathlib (1.0.1)  
pip (7.1.2)  
plac (0.9.1)  
preshed (0.43)    
py (1.4.30)  
pytest (2.8.2)  
setuptools (18.2)  
six (1.10.0)  
spacy (0.99)  
text-unidecode (1.0)  
thinc (3.4.1)  
ujson (1.33)  
wheel (0.24.0)`

**Comment by honnibal** [comment]
In general if you install anything in the main environment, you're going to have a bad time =/

You're probably getting interference from `thinc` being in the main environment. Uninstalling `spacy` won't uninstall its dependencies, even if they were only installed as a requirement. So `pip uninstall spacy` doesn't reset state back to how it was before you did `pip install spacy`.

```
pip install thinc==4.0.0
```

should sort you out. But you should also uninstall `thinc` from the main environment.

**Comment by tabidots** [comment]
Hmm. Well, I kept trying and nothing worked, so eventually I decided to install Anaconda and see if I could get it working that way. The installation went fine, but then when I try to import Spacy, I get this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "//anaconda/lib/python2.7/site-packages/spacy/language.py", line 11, in <module>
    from .vocab import Vocab
  File ".env/lib/python3.4/site-packages/cymem/cymem.pxd", line 1, in init spacy.vocab (spacy/vocab.cpp:16091)
ImportError: No module named cymem.cymem
```

Anaconda explicitly told me that cymem would be installed as part of the package, so this doesn't make any sense. Plus, did the Anaconda installation of Spacy create a venv that uses Python 3.4? I don't want to use Python 3.4.

**Comment by henningpeters** [comment]
Conda still ships version ```0.98``` (we are working on this). I can confirm the cymem ```ImportError```  with spacy 0.98 on anaconda.

Try creating a fresh virtualenv and install via pip instead (worked for me on OSX 10.10.5 Yosemite using Python 2.7.10):

```
virtualenv spacy
source spacy/bin/activate
pip install spacy
python -m spacy.en.download all --force
```

**Comment by tabidots** [comment]
Brilliant, that worked. Thanks!
