### ISSUE TITLE
Empty lemma and zero POS tags

### ISSUE THREAD

**Issue by vered1986** [honnibal/spaCy#174]
I installed spaCy today, after I already had it working on another computer. I tried running this simple example, but I keep getting empty lemmas and all POS tags are zero. What am I doing wrong?

```
ln [1]: from spacy.en import English
ln [2]: nlp = English()
ln [3]: tokens = nlp(u'This is a test sentence.', tag=True, parse=False)
ln [4]: print [token.lemma_ for token in tokens]
[u'', u'', u'', u'', u'', u'']
ln [5]: print [token.tag for token in tokens]
[0, 0, 0, 0, 0, 0]
```

Thanks in advance.

**Comment by honnibal** [comment]
Did you install the data?

**Comment by vered1986** [comment]
I did, using: `python -m spacy.en.download all`

**Comment by honnibal** [comment]
Try

    python -m spacy.en.download --force all

What version are you using?

**Comment by vered1986** [comment]
I tried it too. I used pip to install, so I assume it should be the latest version, right? I can't find a way to check which version is installed.

**Comment by honnibal** [comment]
The best way to check the version is "pip list"

**Comment by vered1986** [comment]
Great, thanks. The installed version is 0.99. On the other computer, where this code works, I have version 0.84 installed.

**Comment by honnibal** [comment]
OS and Python version?

It looks to me like there's some sort of platform problem, which is leaving the models out of alignment, so none of the features are firing.

The other possibility is that somehow the data didn't install correctly. Did you have the right virtualenv active when you issued the download command? You can double check with:

```
python -c "import spacy; print(spacy.__file__)"
```

**Comment by vered1986** [comment]
I installed it without a virtual environment before, and I guess that other versions of Python and the dependencies that are installed on the server were interfering. I tried it in a virtual environment now, and it worked. Thanks for all the help!
