### ISSUE TITLE
Loading custom gazetteer data breaks existing entity matching?

### ISSUE THREAD

**Issue by viksit** [honnibal/spaCy#178]
For instance,

```
a = nlp(u"get me a flight leaving 20th December and arriving on January 5th")
[(i.text, i.label_) for i in a.ents]
[(u'20th December', u'DATE'), (u'January 5th', u'DATE')]
```

Now, if I were to load a custom gazetteer that contains airport codes,

```
a = nlp(u"get me a flight from SFO to LAX leaving 20 December and arriving on January 5th")

[(i.text, i.label_) for i in a.ents]
[(u'SFO', u'AIRPORT'), (u'LAX', u'AIRPORT')]
```

Why would the dates vanish?

**Comment by honnibal** [comment]
Thanks for the report on this. I fixed a different bug related to the interaction between the entity recogniser and the matcher, but I think this seems to be unrelated. Will investigate and let you know.

**Comment by viksit** [comment]
@honnibal any pointers on this?

**Comment by honnibal** [comment]
Sorry for the delay on this. Should be fixed in master, and rolled out onto pip soon.  See Issue #217

**Comment by honnibal** [comment]
Just pushed v0.100, which should have this fixed. If you have any problems, please reopen this and let us know.
