### ISSUE TITLE
Custom Tokenizers

### ISSUE THREAD

**Issue by ashishbaghudana** [honnibal/spaCy#182]
Hi, I have a question regarding the tokenizers. I am using this for biomedical text with a sentence such as `Enhanced expression of AEG-1 via a replication-incompetent adenovirus (Ad.AEG-1) in HeLa cells markedly increased binding of the transcriptional activator p50/p65 complex of NF-kappaB.`

The default tokenizer unfortunately splits **`(Ad.AEG-1)`** into `(`, `Ad`, `.`, `AEG-1` and `)`, which causes sentence splitting also to be at **`.`**. The actual splitting for my purposes should be `(`, `Ad.AEG-1` and `)`.

I was hoping you could give me some help with implementing my own tokenizer, so I can avoid this issue.

**Comment by aliabbasjp** [comment]
It is possible to implement your own tokenizer do search the other threads
they have explained.

**Comment by aliabbasjp** [comment]
def my_split_function(string):
    return string.split()
old_tokenizer = nlp.tokenizer
nlp.tokenizer = lambda string: old_tokenizer.tokens_from_list(my_split_function(string))

**Comment by ashishbaghudana** [comment]
@aliabbasjp Thank you so much!
