### ISSUE TITLE
error in installing spacy

### ISSUE THREAD

**Issue by shruti927** [honnibal/spaCy#199]
I tried installing spacy on ubuntu 14.04 and got the following error:

shrutika@ubuntu:~$ pip install --upgrade spacy
Collecting spacy
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached spacy-0.99.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    headers_workaround.__init__: module references __file__
    
    Installed /tmp/pip-build-kE2fQc/spacy/headers_workaround-0.18-py2.7.egg
    running egg_info
    creating pip-egg-info/spacy.egg-info
    writing requirements to pip-egg-info/spacy.egg-info/requires.txt
    writing pip-egg-info/spacy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/spacy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/spacy.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    package init file 'spacy/tests/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/matcher/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/morphology/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/munge/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/parser/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/serialize/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/spans/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tagger/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokenizer/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokens/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vectors/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vocab/__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kE2fQc/spacy/setup.py", line 231, in <module>
        main(MOD_NAMES, use_cython)
      File "/tmp/pip-build-kE2fQc/spacy/setup.py", line 207, in main
        run_setup(exts)
      File "/tmp/pip-build-kE2fQc/spacy/setup.py", line 190, in run_setup
        headers_workaround.install_headers('murmurhash')
      File "/tmp/pip-build-kE2fQc/spacy/headers_workaround-0.18-py2.7.egg/headers_workaround/__init__.py", line 33, in install_headers
        shutil.copytree(src_dir, dest_dir)
      File "/usr/lib/python2.7/shutil.py", line 177, in copytree
        os.makedirs(dst)
      File "/usr/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/usr/include/murmurhash'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kE2fQc/spacy

What to do next?

**Comment by honnibal** [comment]
Try

    pip install headers_workaround
    pip install --no-cache-dir spacy

Thanks for your patience! We're trying to keep this smooth.

**Comment by shruti927** [comment]
I tried and got this error:

shrutika@ubuntu:~$ pip install headers_workaround
Collecting headers-workaround
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading headers_workaround-0.18.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 148kB/s 
Installing collected packages: headers-workaround
  Running setup.py install for headers-workaround
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-AbWds_/headers-workaround/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mNCNCK-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/headers_workaround
    copying headers_workaround/__init__.py -> build/lib.linux-x86_64-2.7/headers_workaround
    creating build/lib.linux-x86_64-2.7/headers_workaround/murmurhash
    copying headers_workaround/murmurhash/MurmurHash2.h -> build/lib.linux-x86_64-2.7/headers_workaround/murmurhash
    copying headers_workaround/murmurhash/MurmurHash3.h -> build/lib.linux-x86_64-2.7/headers_workaround/murmurhash
    creating build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/halffloat.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/__ufunc_api.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_endian.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/ndarrayobject.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/ndarraytypes.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_interrupt.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_common.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_no_deprecated_api.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/oldnumeric.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/_numpyconfig.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_1_7_deprecated_api.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/__multiarray_api.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_math.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/ufuncobject.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/arrayobject.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_cpu.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/arrayscalars.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/utils.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/old_defines.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/_neighborhood_iterator_imp.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/numpyconfig.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_3kcompat.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/npy_os.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    copying headers_workaround/numpy/noprefix.h -> build/lib.linux-x86_64-2.7/headers_workaround/numpy
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/headers_workaround
    error: could not create '/usr/local/lib/python2.7/dist-packages/headers_workaround': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-AbWds_/headers-workaround/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mNCNCK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-AbWds_/headers-workaround

**Comment by honnibal** [comment]
Do you have python-dev and build-essential installed?

I normally install my things into a virtualenv, but if you're doing a
system installation, you might need to run under sudo? Not that I recommend
this.

**Comment by shruti927** [comment]
Yes I have python-dev and build-essential installed.

Even after running it under sudo I got this:
shrutika@ubuntu:~$ sudo apt-get install headers_workaround
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package headers_workaround

**Comment by pquentin** [comment]
@shruti927 I think the correct command is `sudo pip install headers_workaround`.

@honnibal The pip docs do not mention virtualenvs at all. But I guess it's difficult to explain.

**Comment by honnibal** [comment]
These problems should be addressed in the next release, which finally gets rid of the `headers_workaround` kludge, thanks to @henningpeters redesigning the installation process. We also have a much better CI system in place.

**Comment by vsbiradar** [comment]
Even after installing the headers_workaround it is giving me the same error. Any help please.
