### ISSUE TITLE
Growing memory usage

### ISSUE THREAD

**Issue by jstaker7** [honnibal/spaCy#205]
Since English() takes awhile to load, I have the habit of loading this as a global variable and reusing it when needed, like so:

nlp = English()

for sentence in long_list:
    tokens = nlp(sent)
    do_something(tokens)

But my memory usage grows over time. Started at about ~2GB and I'm at 8GB right now. This is while processesing ~10M sentences. 

Is there some sort of caching that is happening within the class? Is there anything I can do to safely clear it?

**Comment by jstaker7** [comment]
Related to this: I'd like to speed up my process with multithreading. Any recommendations on that front? If the class state is important during processing, I'm afraid an extension of the method above will result in corrupted data:

nlp = English()

def process(sent):
    tokens = nlp(sent)

threads = 8
map(process, long_list)

**Comment by honnibal** [comment]
That memory-use growth is surprising. It may be that a memory leak has been introduced. I'll look into that, thanks.

Multi-threading support is on the roadmap. I'm working on replacing the linear model with a neural network. This will reduce memory usage and should also make multi-threading easier.

**Comment by andreasgrv** [comment]
It might also be a good idea to check that ram consumption isn't simply
caching. Had a similar issue even though I was streaming a file line by
line. http://www.linuxatemyram.com/

**Comment by jstaker7** [comment]
Thank you for excellent response time -- much appreciated. I haven't been able to confirm for certain, but it looks like memory fragmentation is potentially the culprit. This is the first time I've experienced "high water" in python, but it looks like it is a known python gotcha, and probably has nothing to do with Spacy. I had been running my code for 3-4 days so that makes sense.

**Comment by honnibal** [comment]
Thanks for the follow up!
