### ISSUE TITLE
Installation Error "No module named cymem.cymem" El Capitan, Ananconda, spacy-0.99

### ISSUE THREAD

**Issue by vsaxena** [honnibal/spaCy#206]
I am on Mac OSX El Capitan and using Anaconda with a fresh install of python in my home dir.

_MacBook-Pro:anaconda vikram$ which python
/Users/vikram/anaconda/bin/python_

When running
_python -m spacy.en.download all_
I get the error:
_/Users/vikram/anaconda/bin/python: No module named cymem.cymem_

While installing spacy there was a message about possible conflict in cymem package which it automatically resolved.

MacBook-Pro:anaconda vikram$ conda install spacy
Fetching package metadata: ......
Solving package specifications: ......................................
Warning: 4 possible package resolutions (only showing differing packages):
	[u'cymem-1.30-0.tar.bz2', u'murmurhash-0.24-0.tar.bz2'],
	[u'cymem-1.30-py27_0.tar.bz2', u'murmurhash-0.24-0.tar.bz2'],
	[u'cymem-1.30-py27_0.tar.bz2', u'murmurhash-0.24-py27_0.tar.bz2'],
	[u'cymem-1.30-0.tar.bz2', u'murmurhash-0.24-py27_0.tar.bz2'],

Package plan for installation in environment /Users/vikram/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.11              |                0         9.9 MB
    cloudpickle-0.1.1          |           py27_0          15 KB
    conda-env-2.4.5            |           py27_0          24 KB
    cymem-1.30                 |                0          39 KB
    murmurhash-0.24            |                0          15 KB
    plac-0.9.1                 |           py27_0          31 KB
    setuptools-18.5            |           py27_0         343 KB
    text-unidecode-1.0         |           py27_0          62 KB
    conda-3.18.9               |           py27_0         176 KB
    preshed-0.44               |           py27_0          85 KB
    thinc-4.0.0                |           py27_0         207 KB
    spacy-0.99                 |      np110py27_0         2.6 MB
    ------------------------------------------------------------
                                           Total:        13.5 MB

**Comment by vsaxena** [comment]
There seems to be references to python3.5 in the conda-meta data for this module...
Perhaps it needed to resolve to [u'cymem-1.30-py27_0.tar.bz2', u'murmurhash-0.24-py27_0.tar.bz2'] when it chose which package to install?

MacBook-Pro:anaconda vikram$ more conda-meta/cymem-1.30-0.json 
{
  "arch": "x86_64", 
  "binstar": {
    "channel": "main", 
    "owner_id": "5617c51fb7eda558af8b2827", 
    "package_id": "562b7c76ab59365f7a302252"
  }, 
  "build": "0", 
  "build_number": 0, 
  "channel": "https://conda.anaconda.org/spacy/osx-64/", 
  "depends": [
    "python >=2.7"
  ], 
  "files": [
    "lib/python3.5/site-packages/cymem-1.30-py3.5.egg-info", 
    "lib/python3.5/site-packages/cymem/__init__.pxd", 
    "lib/python3.5/site-packages/cymem/__init__.py", 
    "lib/python3.5/site-packages/cymem/__pycache__/__init__.cpython-35.pyc", 
    "lib/python3.5/site-packages/cymem/cymem.c", 
    "lib/python3.5/site-packages/cymem/cymem.cpython-35m-darwin.so", 
    "lib/python3.5/site-packages/cymem/cymem.pxd", 
    "lib/python3.5/site-packages/cymem/cymem.pyx"
  ], 
  "license": "MIT", 
  "link": {
    "source": "/Users/vikram/anaconda/pkgs/cymem-1.30-0", 
    "type": "hard-link"
  }, 
  "machine": "x86_64", 
  "md5": "3f646ce5d6b86c600b92a23697b96498", 
  "name": "cymem", 
  "operatingsystem": "darwin", 
  "platform": "osx", 
  "requires": [], 
  "size": 39690, 
  "subdir": "osx-64", 
  "target-triplet": "x86_64-any-darwin", 
  "url": "https://conda.anaconda.org/spacy/osx-64/cymem-1.30-0.tar.bz2", 
  "version": "1.30"
}

**Comment by vsaxena** [comment]
Problem seems to be in the way the packages are listed in the repodate file.

https://conda.anaconda.org/spacy/osx-64/repodata.json 

has an entry for 
"cymem-1.30-0.tar.bz2": with "depends": [
"python >=2.7"
],
before this one. 
"cymem-1.30-py27_0.tar.bz2":  with "depends": [
"python 2.7*"
],

The first one seems to be selected during installation and it installs the python 3.5 libraries.
 /Users/vikram/anaconda/pkgs/cymem-1.30-0/lib/python3.5/

Same for murmurhash,

"murmurhash-0.24-0.tar.bz2" is listed before "murmurhash-0.24-0.tar.bz2" and it is also installing python 3.5 libraries.
/Users/vikram/anaconda/pkgs/murmurhash-0.24-0/lib/python3.5/

**Comment by henningpeters** [comment]
Thanks for this, this obviously doesn't look right. We are not that experienced in building conda packages yet, in case you want to help out can you take a look at our conda build script at ```https://github.com/spacy-io/spaCy-conda/blob/master/.travis.yml``` and see whether there is something to improve?

**Comment by vsaxena** [comment]
I am brand new to Anaconda (just installed to it to get spacy going) and its past bed time here in the US, but here is what a quick reading suggests (I have not tried to build it yet).

http://conda.pydata.org/docs/spec.html#repository-structure-and-index
-The command conda index can be used to create such an index from the conda packages within a directory._

It seems like the director(ies) which contains the python version specific packages, also contain the  package without the versions and when the "conda index" runs, they too get included. I haven't figured out where the conda index runs in the build process yet (or there may be some other command which also has a similar effect).

The unversioned packages appear for all of the following:
https://conda.anaconda.org/spacy/osx-64/repodata.json

cymem-1.30-0.tar.bz2
headers_workaround-0.18-0.tar.bz2
murmurhash-0.24-0.tar.bz2
preshed-0.44-0.tar.bz2
thinc-4.0.0-0.tar.bz2

The order in which they get included  in the repodata, may depend on how they get listed in the dir.

I think if those unversioned package files are located in a different dir, they would not end up in the repodata.

**Comment by honnibal** [comment]
This is some great debugging — we really appreciate this, thanks!

If you just want to get up and running, it seems easier to use `pip` instead of `conda`, as it seems our package on `conda` isn't correct. While we sort the issue out, I suggest the following:

1. Start with a clean conda environment

    `conda create --name myenv numpy`

The `conda create` command requires you to specify at least one package to install. I always find this super confusing. The important thing here is that you can't write `spacy`! If you do, `spacy` will be installed from the conda package, when we want to install it from pip.

2. Activate the environment

`source activate myenv`

2. Install with pip

`pip install spacy`

3. Install data

`python -m spacy.en.download --force all`

**Comment by vsaxena** [comment]
Thanks. That worked.

Did have to add the unicode conversion for the 1st example
doc = nlp(**unicode**('Hello, world. Here are two sentences.'))

Was Getting a type mismatch error 
_tokens = self.tokenizer(text)_
_TypeError: Argument 'string' has incorrect type (expected unicode, got str)_

**Comment by henningpeters** [comment]
All spaCy documentation assumes Python3 unicode conventions - thanks, we should make that clearer. Adding a ```from __future__ import unicode_literals``` makes your Python2 code future-proof.

**Comment by vsaxena** [comment]
Thanks for the pointers on __\_\_future\_\___
Working fine now.
