### ISSUE TITLE
Specify different location for data download

### ISSUE THREAD

**Issue by danvalente** [honnibal/spaCy#208]
For v0.99, I can't seem to figure out how to specify a different location in which to download the data, for instance, I'd like it to go in `mnt/data/spacy/en` instead of the default location.  I've tried `install_data`, but can't quite get it to work. 

Is this possible?

**Comment by henningpeters** [comment]
Unfortunately, the download script in ```0.99.0``` doesn't allow to specify alternate locations, this will likely change in future releases, thanks for mentioning the need for this. Until then you could run ```python -m spacy.en.download --force```, copy the spacy data folder (obtain it via ```python -c "import spacy; import os; print(os.path.join(os.path.dirname(spacy.__file__), 'en', 'data'))"```) to a different location and call ```English(data_dir='path_to_data')```.

Regarding ```install_data```: What does this refer to, are the docs maybe outdated?

**Comment by danvalente** [comment]
The docs may be outdated, since `help(spacy.en.download)` mentions `install_data` as a function, but I was able to get things to work by doing this:
`python -c "from spacy.en.download import install_data, ALL_DATA_DIR_URL; install_data(ALL_DATA_DIR_URL,'/mnt/data/spacy/en', '/mnt/data/spacy/en/en_data_all-0.9.9.tgz)"`

**Comment by henningpeters** [comment]
That looks even better than my proposal, thanks. Please note that this is private/undocumented API and might break in the future.

**Comment by danvalente** [comment]
Got it.  Thanks!

**Comment by henningpeters** [comment]
Btw: in spaCy >= 0.100.2 we introduced an official way to programmatically control the location of the installed models:

```
import sputnik
import spacy
sputnik.install('spacy', spacy.about.__version__, 'en_default', data_path=data_path)
nlp = spacy.load('en_default', via=data_path)
```

where ```data_path``` is your custom model directory.

Please note that ```sputnik.install()``` will download the model first in case its not already installed.

**Comment by danvalente** [comment]
This is great. Thanks a ton @henningpeters!
