### ISSUE TITLE
Usage Examples return TypeError

### ISSUE THREAD

**Issue by besirkurtulmus** [honnibal/spaCy#212]
In this example in the website: https://spacy.io/#example-use tells us to create a doc as the following: 
`doc = nlp('Hello, world. Here are two sentences.')`
This returns the error:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/someuser/Desktop/spacy/env/lib/python2.7/site-packages/spacy/language.py", line 234, in __call__
    tokens = self.tokenizer(text)
TypeError: Argument 'string' has incorrect type (expected unicode, got str)
`
I can easily fix this error by declaring the string unicode by:
`doc = nlp(u'Hello, world. Here are two sentences.')`
Is this behaviour normal? If so I think it would be a good idea to update the docs on the website.

**Comment by henningpeters** [comment]
spaCy is written with parallel support for Python 2 and 3 in mind. Now, string/unicode handling in Python 2 and Python 3 is different from each other. In the examples spaCy uses py3-style strings, which won't work at the same time in py2.

An easy way to get Python 3-style string/unicode handling in Python 2 is to include this line at the top of your source:

```
from __future__ import unicode_literals
```

Using this in the rest of your application also ensures that your Python 2 sources are easier to port to Python 3 in the future.

For more information on future import see http://python-future.org/unicode_literals.html and on string/unicode handling in general see http://lucumr.pocoo.org/2014/1/5/unicode-in-2-and-3/

**Comment by besirkurtulmus** [comment]
Thanks for the info.

Like you said, the docs should be clearer about this and leave no confusion.
