### ISSUE TITLE
Installing with pip fails, npy_1_7_deprecated_api.h: No such file or directory

### ISSUE THREAD

**Issue by mmalhotra** [honnibal/spaCy#216]
Getting the following error while installing spacy
I have this numpy: numpy 1.10.2 
Failed building wheel for spacy
Failed to build spacy
Installing collected packages: spacy
  Running setup.py install for spacy
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-zsp76U/spacy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HAkROy-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'spacy/tests/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/matcher/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/morphology/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/munge/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/parser/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/serialize/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/spans/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tagger/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokenizer/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/tokens/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vectors/__init__.py' not found (or not a regular file)
    package init file 'spacy/tests/vocab/__init__.py' not found (or not a regular file)
    running build_ext
    building 'spacy.lexeme' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I. -I/usr/include -I/usr/include/python2.7 -c spacy/lexeme.cpp -o build/temp.linux-x86_64-2.7/spacy/lexeme.o -O3 -Wno-strict-prototypes -Wno-unused-function
    cc1plus: warning: command line option ‘-Wno-strict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/python2.7/numpy/ndarrayobject.h:17:0,
                     from /usr/include/python2.7/numpy/arrayobject.h:4,
                     from spacy/lexeme.cpp:259:
    /usr/include/python2.7/numpy/ndarraytypes.h:1804:36: fatal error: npy_1_7_deprecated_api.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-zsp76U/spacy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), _

**Comment by honnibal** [comment]
Hmm. This is pretty confusing.

Could you give me more steps prior? Are you using a virtualenv? Are you using pip, or building from source?

**Comment by mmalhotra** [comment]
Not using virtualenv, I just installed python-dev and then started installation from pip (I also upgraded Numpy but to no avail)
Conda however works.

**Comment by henningpeters** [comment]
I suspect there is something wrong with your numpy version or installation. In your error it says:

```
/usr/include/python2.7/numpy/ndarraytypes.h:1804:36: fatal error: npy_1_7_deprecated_api.h: No such file or directory
```

But numpy's ndarraytypes.h from version 1.10.2 doesn't even have a line 1804: https://github.com/numpy/numpy/blob/5667fbafb5d84e3a412a07aac72c769baa590579/numpy/core/include/numpy/ndarraytypes.h

Some thoughts:

1) Could it be that you are using an outdated stock debian/ubuntu version of numpy?

Could you run ```python -c "import numpy; print(numpy.__version__)"``` and share the result?

It could be that there is a numpy installation != 1.10.2 lurking around on your system, often those unwanted outdated packages come via from system package managers such as apt, yum, etc.

Generally, the easiest way to avoid Python packages from distributions is to create a virtualenv and install everything in there via pip in it from scratch.

2) You could also try setting ```NPY_NO_DEPRECATED_API``` environment variable to ```0x00000008``` (enforce >= 1.8 API version). This should make numpy not try to look for the file.

3) ```npy_1_7_deprecated_api.h``` file somehow got lost / you have a broken installation

Could you check whether you have a ```npy_1_7_deprecated_api.h``` file your numpy include dir (how to find the include dir, as in your error: ```/usr/include/python2.7/numpy``` and/or via running: ```python -c "import numpy; print(numpy.get_include())"```?

If the file isn't there, please reinstall numpy and ensure the file pops up.

**Comment by henningpeters** [comment]
Btw: Which OS, (if Linux: distribution) and version are you using? That would help us reproducing this issue.

**Comment by mmalhotra** [comment]
python -c "import numpy; print(numpy.__version__)"
Produces the output
1.10.1

I'm using Wheezy Debian. 
I tried with virtualenv and it worked, I think your 1st thought is correct.

**Comment by henningpeters** [comment]
I was able to reproduce your issue on Debian wheezy. It's not a debian packacking bug as I had assumed, but instead a bug in spaCy (or more precisely, headers_workaround) that already got fixed on master branch and will make it into next release. Thanks for reporting it!
