### ISSUE TITLE
Pronoun Detection

### ISSUE THREAD

**Issue by alanhdu** [honnibal/spaCy#22]
It seems that `spaCy` counts all pronouns as normal nouns.

```Python
import spacy.en
nlp = spacy.en.English()

In [34]: for tok in nlp(u"You and I make us"):
   ....:     print tok.string, tok.pos
   ....:     
You  6
and  4
I  6
make  10
us 6

In [35]: from spacy.parts_of_speech import PRON, NOUN

In [36]: NOUN, PRON
Out[36]: (6, 8)
```

**Comment by honnibal** [comment]
I'll make this clearer in the documentation.

The .pos attribute gives you tags from Google's universal tag set. The .tag attribute gives you the "ordinary" language-specific 45 tag Penn Treebank tag set.

**Comment by alanhdu** [comment]
Hm... I thought that `PRON` was in Google's tag set. Wouldn't that mean `.pos` should recognize it?

**Comment by honnibal** [comment]
Hmm you're right. I thought I copy-pasted the mapping, but I must have made an error somehow. I'll fix this and retrain my models.

**Comment by tingofurro** [comment]
Hey I was trying to detect pronouns too, and it returns that the pos_ is a noun. Is that normal?
I ran the same example:

for tok in nlp(u"You and I make us"):
...     print tok.orth_, tok.pos_
...
You NOUN
and CONJ
I NOUN
make VERB
us NOUN

Not a big deal, just wanted to know, spacy is awesome!

**Comment by robinsloan** [comment]
Same experience here—I can't get spaCy to detect pronouns at all. Is this a big or is there some subtlety we're missing?
