### ISSUE TITLE
invalid pointer

### ISSUE THREAD

**Issue by AvinashGupta** [honnibal/spaCy#236]
i tried to import english model at ubuntu system like:
```
from spacy.en import English
nlp  = English()
```
it gives me:
```
Error in `python': free(): invalid pointer: 0x0000000005fff4a8 ***
```

**Comment by henningpeters** [comment]
Thanks for issuing the report. Could you share a bit more information regarding your system, specifically:

- Python version (including whether its a 32 or 64 build)
- Ubuntu version
- output of ```pip list``` or in case you don't use pip an equivalent overview of installed packages with version numbers

**Comment by AvinashGupta** [comment]
Thanks Henning for your quick replay
I am running it at aws ubuntu 64-bit server, small instance, its specs are
```
file /sbin/init
/sbin/init: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=7a4c688d009fc1f06ffc692f5f42ab09e68582b2, stripped
```
python i have installed is `Python 2.7.6 [GCC 4.8.2] on linux2` with

    >>> sys.maxsize > 2**32
    True
and
```
pip list
argparse (1.2.1)
cloudpickle (0.1.1)
cymem (1.30)
murmurhash (0.26.0)
numpy (1.10.4)
pip (1.5.4)
plac (0.9.1)
preshed (0.46.1)
semver (2.2.1)
setuptools (2.2)
six (1.10.0)
spacy (0.100.2)
sputnik (0.8.2)
text-unidecode (1.0)
thinc (4.2.0)
ujson (1.35)
wsgiref (0.1.2)
```
every thing installed well when tried
```
>>> from spacy.en import English
>>> nlp = English()
```
i waits for 1 minute and then throws error:
```
*** Error in `python': free(): invalid next size (normal): 0x000000000dfff920 ***
Aborted (core dumped)
```
i have also tried with spacy 0.99 through source code but error remains same

**Comment by henningpeters** [comment]
Thank you. Everything looks ok. What worries me a bit is that EC2 t2.small instances only have ~2 GB memory. On my system spaCy consumes easily 1,6 GB. Could you observe your free memory and/or try spaCy on a larger instance?

**Comment by AvinashGupta** [comment]
Yes, now its working well at EC2 medium instance with 4GB RAM. Is there any way to run it at 2GB RAM server by reducing data set or something alike?

**Comment by honnibal** [comment]
It depends what parts you're using. If you're using everything, then no unfortunately we don't have a way to reduce the memory requirements at this time.

If you're not using the word vectors, you can replace the file `vec.bin` file with a 0 bytes one (there needs to be an API for not loading the word vectors...). If you're not using any parser functionality (which includes sentence boundary detection and the `noun_chunks` iterator) you can prevent loading the parser by passing `parser=False` to the call to `English.__call__`, or by replacing the `parser` object with `None`.

**Comment by AvinashGupta** [comment]
Great, thanks guys for helping, i got it.

**Comment by henningpeters** [comment]
Even though we found the root cause the error message leaves some room for improvements, hence I created #239.
