### ISSUE TITLE
token.lemma_ with the token "didn't" does not exist

### ISSUE THREAD

**Issue by NSchrading** [honnibal/spaCy#24]
The token "didn't" is correctly separated into ["did", "n't"], but in this case the lemma for "did" does not correctly register as "do", instead it is an empty string.
`tokens = nlp("didn't")`
`print(tokens[0].lemma_)`
`>>> empty string`

However it works when the token is just "did"
`tokens = nlp("did")`
`print(tokens[0].lemma_)`
`>>> do`

And "isn't" works perfectly, correctly being split as ["is", "n't"] with the lemma "be" for token[0]
`tokens = nlp("isn't")`
`print(tokens[0].lemma_)`
`>>> be`

**Comment by honnibal** [comment]
Thanks, fixed.

I've corrected the data file for that entry, to load its lemma, and fixed the error that caused the lemma to be empty when the data was missing.

The corrected data will be uploaded in the next release, which should be within the next 48 hours.
