### ISSUE TITLE
Suspected inaccuracy in the gazetteer

### ISSUE THREAD

**Issue by savkov** [honnibal/spaCy#243]
I found the following entry in `<repo>/spacy/data/en_default-1.0.7/vocab`

```
    "Facebook": [
        "ORG",
        {},
        [
            [{"lower": "facebook"}]
        ]
    ],
     "Blizzard": [
        "ORG",
        {},
        [
            [{"orth": "Facebook"}]
        ]
    ],
```

**Comment by honnibal** [comment]
Thanks, fixed!

**Comment by henningpeters** [comment]
I just uploaded a new model. Please update via ```python -m spacy.en.download --force```. To check the installed version of your model you can run ```python -m sputnik --name spacy find```. Latest version is ```1.0.8```.
