### ISSUE TITLE
pos tagging issue

### ISSUE THREAD

**Issue by bowlesbe** [honnibal/spaCy#28]
words like i.e., cause major issues with pos tagging because they are just ignored, providing a faulty mapping between words and pos for the rest of the words in the sentence

**Comment by honnibal** [comment]
wat

    >>> import spacy.en
    >>> nlp = spacy.en.English()
    >>> tokens = nlp(u'That i.e. this')
    >>> len(tokens)
    >>> len(tokens)
    4
    >>> for t in tokens:
    >>> for t in tokens:
    ...   print t.orth_, t.pos_
    ... 
    That DET
    i.e NOUN
    . PUNCT
    this DET

The tokenization is incorrect here --- the period should belong to "i.e.". I'll update the tokenizer, adding this as a special-case. But: what do you mean by "ignored"? Are you getting something different from this? It sounds pretty serious...
