### ISSUE TITLE
Slang

### ISSUE THREAD

**Issue by JamesCarl** [honnibal/spaCy#29]
Is there a method you would prefer for individuals to add slang to parts of speech library? 
Would you allow for this/ how would I go about doing it?
i.e do contractions like 'sup?' get reduced to a verb or a noun?

**Comment by honnibal** [comment]
There's functionality to support handling special cases in arbitrary, user-defined ways. But, I haven't wired this up properly yet.

The tokenizer reads a data file that looks like this: https://github.com/honnibal/spaCy/blob/master/lang_data/en/specials.json

The key form maps to a list of tokens. You can specify the form, lemma, POS tag etc for each token.

So, you can do any sort of non-concatenative morphology you want. You can do:

"sup": [{"F": "what"}, {"F": "is"}, {"F": "up"}]

If you want.

But, as I said, this isn't set up in a nice way yet. You can find the specials.json file spaCy is currently loading under the spacy/en/data file, which is probably installed into your virtualenv. You can find the directory with "python -e import spacy.en; print spacy.en.__file__".

**Comment by JamesCarl** [comment]
That is very helpful. Thanks for your reply will be sure to mention you and your help in the paper! Keep up the awesome work!
