### ISSUE TITLE
Lemmatizer is converting all PRP tokens to the lemma -PRON-

### ISSUE THREAD

**Issue by cyrus** [honnibal/spaCy#31]
No sure if this is a bug or a feature, but just thought I would note it:

`>>>tokens = nlp(u"I see you.", tag=True, parse=False)`
`>>>tokens[0].lemma_`
`'-PRON-'`

`>>>tokens[2].lemma_`
`'-PRON-'`

Shouldn't the lemmas be "I" and "you"?

Thanks for the nice work on spaCy!

-Cyrus

**Comment by honnibal** [comment]
Lemmas are not defined for WordNet, so I had to make up the policy. I decided to do it this way. Otherwise you'd have to guess what "she", "they", "it" etc resolved to.

In a lot of other WordNet lemmatizers, "his" gets lemmatized to "hi", because it's not in the lexicon!
