### ISSUE TITLE
token boolean features

### ISSUE THREAD

**Issue by transcranial** [honnibal/spaCy#37]
The example of boolean features `(is_alpha, is_digit, is_lower, is_title, is_upper, is_ascii, is_punct, like_url, like_num)` shown on the [quickstart page](http://honnibal.github.io/spaCy/quickstart.html) doesn't work for me:

```
>>> lexeme = nlp.vocab[u'Apple']
>>> lexeme.is_alpha, is_upper
True, False
>>> tokens = nlp('Apple computers')
>>> tokens[0].is_alpha, tokens[0].is_upper
>>> True, False
>>> from spact.en.attrs import IS_ALPHA, IS_UPPER
>>> tokens.to_array((IS_ALPHA, IS_UPPER))[0]
array([1, 0])
```

For example, I'm getting: `AttributeError: 'spacy.tokens.Token' object has no attribute 'is_alpha'`

Instead, I'm calling `from spacy.orth import *` and then calling, for example, `is_punct(token)`. There is also the inconsistency of `spacy.orth.like_number` as `like_num` listed under boolean features in the quickstart page.

**Comment by syllog1sm** [comment]
Thanks.

Added Token.check_flag method, used like so:

    >>> tokens = nlp('Apple computers')
    >>> tokens[0].check_flag(IS_ALPHA)
    True

This is a less convenient API than the token.is_alpha, but plays more nicely with user and language-specific flags. I want to avoid sub-classing Token per language, but different languages will want different flag features.

If you have strong feelings either way on this, I'm happy to listen.

**Comment by transcranial** [comment]
Thanks!

Definitely makes sense not to subclass Token per language. Another option could be to have the `token.is_alpha` style API for those flags common to all languages and some kind of language specific flag API like `token.lang_spec(FLAG)`, but this could be unnecessarily confusing.
