### ISSUE TITLE
Idea: Switch orth / orth_, tag / tag_, etc from int / unicode to unicode / int (please debate)

### ISSUE THREAD

**Issue by syllog1sm** [honnibal/spaCy#38]
SpaCy maintains a global mapping of strings to integers. Currently the integer-value is named "foo", and the string value is named "foo_".

I now think I prefer to have the string value named "foo", and the integer value named "foo_". I had convinced myself that it should be possible to avoid using the string attributes almost entirely, but in my own use, I find myself needing these attributes a lot.

What do you think? Should I keep token.orth as the integer ID, or should I move the integer IDs to the underscored attributes?

**Comment by cyrus** [comment]
I vote to move the integers to the underscored attributes. I use them less often, so it will save my left pinky a lot of work!

**Comment by transcranial** [comment]
I agree, I think it would be more intuitive to have the integer value as the underscored name rather than as the main name.

**Comment by suchow** [comment]
:+1: on swapping them.

**Comment by flor385** [comment]
I don't think they should be swapped. While I would prefer to have ints underscored, changing it now breaks the API, and it is really not a very difficult convention to get used to.

**Comment by syllog1sm** [comment]
I get that it breaks the API, and this is unfortunate. But I'd rather introduce breaking changes now than live with them forever.

**Comment by flor385** [comment]
Sure...

Also, after some more consideration, I think that having ints as default values for each tag makes a lot of sense since most of the time it's ints one wants to work with, and not unicode strings.

**Comment by viksit** [comment]
Yeah, agreed that the keyword_ should represent ints and keyword should be the string value. It's going to cause some pain to change APIs though :8ball:

**Comment by NSchrading** [comment]
I guess I would vote for the change as well. When I first started using spaCy, I was initially confused why using .lemma/.lower/etc was giving me a number and not a string as expected. I think it makes more sense for the string value to be named "foo", and the integer value to be named "foo_", especially for new users.

**Comment by ms8r** [comment]
Two weeks ago I would have said "yes, please swap" but now I'm thinking "please keep as is". The reason is less that I got used to it but more that my work focus has shifted from "data exploration" to "data processing". For the exploratory work the underscores where a bit of a pain but for the processing (which I believe will be the bigger portion) the current convention makes perfect sense.
