### ISSUE TITLE
Error when downloading data a second time

### ISSUE THREAD

**Issue by suchow** [honnibal/spaCy#41]
Steps to replicate:
1. Create a virtual environment.
2. Install spaCy.
3. Download the data.
4. Create a new virual environment.
5. Download the data.

The new data is written into the same temporary folder as the old data, leading to an shutil error. It should probably either (1) check if the right data is already available and use it instead redownloading it, or (2) overwrite the existing data. Maybe you can track versions using their MD5 hash or the spaCy version or something like that (e.g., installing downloading data into `/tmp/spaCy/v0.7/`.

I'm on OS X 10.10.3, spaCy 0.70, Python 2.7.9.

**Comment by honnibal** [comment]
Thanks, fixed in v0.80
