### ISSUE TITLE
ValueError spacy.en.English() instantiation, version 0.70

### ISSUE THREAD

**Issue by AWNystrom** [honnibal/spaCy#45]
I just upgraded to 0.70, and when I try creating an instance of spacy.en.English, like this:

import spacy.en
nlp = spacy.en.English()

this happens:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-c68587acddc5> in <module>()
----> 1 nlp = spacy.en.English()

//anaconda/lib/python2.7/site-packages/spacy/en/__init__.pyc in __init__(self, data_dir)
     74         else:
     75             tok_data_dir = path.join(data_dir, 'tokenizer')
---> 76             tok_rules, prefix_re, suffix_re, infix_re = read_lang_data(tok_data_dir)
     77             prefix_re = re.compile(prefix_re)
     78             suffix_re = re.compile(suffix_re)

//anaconda/lib/python2.7/site-packages/spacy/util.pyc in read_lang_data(data_dir)
     14 def read_lang_data(data_dir):
     15     with open(path.join(data_dir, 'specials.json')) as file_:
---> 16         tokenization = json.load(file_)
     17     prefix = read_prefix(data_dir)
     18     suffix = read_suffix(data_dir)

//anaconda/lib/python2.7/json/__init__.pyc in load(fp, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    288         parse_float=parse_float, parse_int=parse_int,
    289         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook,
--> 290         **kw)
    291 
    292 

//anaconda/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336             parse_int is None and parse_float is None and
    337             parse_constant is None and object_pairs_hook is None and not kw):
--> 338         return _default_decoder.decode(s)
    339     if cls is None:
    340         cls = JSONDecoder

//anaconda/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

//anaconda/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    380         """
    381         try:
--> 382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
    384             raise ValueError("No JSON object could be decoded")

ValueError: Expecting property name: line 567 column 1 (char 15406)

**Comment by syllog1sm** [comment]
Please run:

    $ python -m spacy.en.download all

There's an error in a data file that's in the pip version. It will be fixed in the next release, which has been delayed slightly. I hope to have it out in the next few days.

**Comment by AWNystrom** [comment]
Thank you much!
