### ISSUE TITLE
Collapsed Dependencies

### ISSUE THREAD

**Issue by AWNystrom** [honnibal/spaCy#47]
Might you might allow for collapsed dependencies to easily be gotten from output of the dependency parser via some option?

**Comment by honnibal** [comment]
The current roadmap is to do semantic role labelling instead.

Is there a reason you need the collapsed dependencies in particular?

**Comment by AWNystrom** [comment]
I've just them for a task and was wondering whether I'd be able to easily
switch to spaCy for it. Are they seen as a deprecated concept?

**Comment by honnibal** [comment]
It's really something the Stanford tools provide, but hasn't been taken up so much by other researchers.

I think for many tasks it's a more useful output than basic dependencies, but for those tasks semantic dependencies are usually better still.

**Comment by AWNystrom** [comment]
Fair enough :) I have a question about the output of your parser. Is this where I should ask such questions, or do have a forum or something?

**Comment by honnibal** [comment]
I've decided to try hosting this on Reddit, instead of the usual solutions (mailing list, Google Groups, etc).

https://www.reddit.com/r/spacynlp/

You can write your question here if you prefer, or you can try out posting it on the new subreddit.

**Comment by bradjonesca** [comment]
Why not Gitter right here on GitHub?
