### ISSUE TITLE
Installing on a system with py2 and py3

### ISSUE THREAD

**Issue by bollwyvl** [honnibal/spaCy#48]
I am building up a Dockerfile which includes spacy based on the [docker/scipyserver](https://registry.hub.docker.com/u/ipython/scipyserver/).

The ipython developers support both python 2 and 3, so I figured I'd follow along and install spacy into both.

However, I have found that only the install that goes last actually sticks:

```Dockerfile
# install requirements
RUN pip install spacy && pip3 install spacy

# downloads a bunch of data
RUN python -m spacy.en.download && python3 -m spacy.en.download
```

This will always fail, as the python2 is no longer importable. Or more simply:
```Dockerfile
# install requirements
RUN pip install spacy && pip3 install spacy
RUN python -c "import spacy"
```

For now, I'm getting away with just supporting python3, but this might be something worth looking into.

Thanks for all the hard work!

**Comment by honnibal** [comment]
Does this work with other libraries?

**Comment by elyase** [comment]
According to [this issue](https://github.com/ipython/docker-notebook/issues/35), `pip install spacy` also installs the py3 version. To get the py2 version one should go with:
```
pip2 install spacy
```
