### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by emmanuelyera** [honnibal/spaCy#54]
I was running spacy through some sentences and saw that the sentence below is throwing a ValuerError.

from spacy.en import English
spacy_nlp = English()
text = u'Talks given by women had a slightly higher number of questions asked (3.2$\\pm$0.2) than talks given by men (2.6$\\pm$0.1).'
tokens = spacy_nlp(text)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spacy/en/__init__.py", line 195, in __call__
    self.mwe_merger(tokens)
  File "/usr/local/lib/python2.7/site-packages/spacy/multi_words.py", line 8, in __call__
    tokens.merge(m.start(), m.end(), tag, m.group(), entity_type)
  File "spacy/tokens.pyx", line 329, in spacy.tokens.Tokens.merge (spacy/tokens.cpp:6701)
ValueError: max() arg is an empty sequence

I have the newest spacy installed and up to date requirements.

**Comment by honnibal** [comment]
Thanks, I'll look into this.

In the meantime you can work around this by turning off the multi-word expression merging:

    tokens = spacy_nlp(text, merge_mwes=False)

**Comment by emmanuelyera** [comment]
Great thanks!

**Comment by honnibal** [comment]
Fixed in v0.83. Be sure to redownload the data.

Note that v0.83 has merge_mwes=False by default, so if you do want the multi-word expressions, supply merge_mwes=True to English.__call__.

**Comment by emmanuelyera** [comment]
Great! Thanks!
