### ISSUE TITLE
Support for collapsed dependencies

### ISSUE THREAD

**Issue by elyase** [honnibal/spaCy#60]
It would be great to have support for collapsed dependencies similar to Stanford CoreNLP. For example in the sentence:
```
"I am moving to Florida"
```
"Florida" and "moving" aren't directly related because of the "to" particle(`florida.head` is `to`). I think the API can work like this:
```python
>>> florida.dependencies(moving)
['prep_to']
```

Then one could do:
```python
if 'prep_to' in florida.dependencies(moving):
   ...
```

**Comment by honnibal** [comment]
I'm reluctant to support this, because it seems one too many representations. The roadmap is to support semantic role labels, constituency parse, and surface-syntactic dependencies.

I'll think about providing an API to restructure the parse tree, so that this can be supported by extension.

**Comment by elyase** [comment]
I think semantic role labels and surface-syntactic dependencies should be enough for my use case.

**Comment by scottyli** [comment]
@honnibal semantic role labels would be awesome, what does the roadmap look like?

**Comment by honnibal** [comment]
Well, the good news is there's lots of good stuff coming. The bad news is
it's pushed SRL down a bit.

- Knowledge-based NER
- Multi-lingual
- Stablise 1.0 API
- Domain adaptation
- Theano integration, neural network models
- SRL

The better news is SRL isn't so much work, given recent research. If you
can put in a weekend or two we could probably get this done:
http://alt.qcri.org/semeval2014/cdrom/pdf/SemEval034.pdf

The idea is to learn the SRL as a projective tree, by giving up on some of
the relations.

What we need:
- Survey the papers implementing similar tree approximations
- Pick the best one
- Implement the data transform

If you can do that initial spadework, I'd be happy to run the experiments.
I can supply sample data for the transformation.

**Comment by scottyli** [comment]
@honnibal i might give this a shot. would you still recommend the tree approximation approach?
