### ISSUE TITLE
Vocabulary indexing

### ISSUE THREAD

**Issue by ms8r** [honnibal/spaCy#65]
Firstly, many thanks for developing spaCy and making it available - really great stuff!

Now to the issue (which may not be an issue at all but just my ignorance...): 

I was assuming that the integers provided by the non-underscore version of the `token` attributes `orth`, `norm`, and `lower` are vocabulary indices, equivalent to a lexeme's `id` attribute.  However, when using a token's `norm` in this way I get different results (this on the 0.84 version):
```python
from spacy.en import English
nlp = English()
tokens = nlp(u'fruit flies like bananas')
tokens[0].norm
#[Out]# 6463
lex = nlp.vocab[tokens[0].norm]
lex.id
#[Out]# 6463
lex.norm
#[Out]# 8462
lex.norm_
#[Out]# u'Ariel'
lex = nlp.vocab[tokens[0].norm_]
lex.id
#[Out]# 4875
lex = nlp.vocab[u'fruit']
lex.id
#[Out]# 4875
lex = nlp.vocab[4875]
lex.norm_
#[Out]# u'fruit'
```
So using the token's unicode representation for a vocabulary lookup results in an `id` that can be used for a reverse lookup. Is it intentional that `orth`, `norm`, `lower` integers seem to have no relation to the `id` values? If so - what do they represent?  As mentioned above, probably my ignorance...

**Comment by honnibal** [comment]
Hey,

This should probably be clearer in the docs.

The .orth, .norm etc properties can be loked up in the StringStore ---
they're array indices for the string. The .id attribute is the array index
of the Lexeme.

So:

vocab[lex.id].orth == lex.orth
vocab.strings[lex.orth] == lex.orth_

The dicts do a typecheck to map both strings and ints:

vocab['apple'].orth == vocab.strings['apple']

Clearer?

**Comment by ms8r** [comment]
Perfect - thanks!
