### ISSUE TITLE
How to uninstall spaCy?

### ISSUE THREAD

**Issue by hwsamuel** [honnibal/spaCy#70]
I used pip to install spaCy. To remove it, I ran pip with the uninstall option. However, how do I reverse/remove the python -m spacy.en.download command?

**Comment by honnibal** [comment]
Hey,

Sorry, I didn't realise the data would still be resident, but I've just checked and you're right. I'll fix this.

In the meantime, the data resides in the package directory, which you can find with:

    python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"

If you want a single command, try this:

    rm -rf python -c "from distutils.sysconfig import get_python_lib; import os.path; print(os.path.join(get_python_lib(), 'spacy'))" 

The python command should build the path to the spacy directory, and then rm -rf should remove it.

**Comment by honnibal** [comment]
Fix to this has now been merged into master.

We now note the installed data in pip's RECORDS file, so that the data will be cleaned up upon pip uninstall.

**Comment by hwsamuel** [comment]
Excellent thanks. By the way, when I ran the single command above, I got an "invalid option, -c" error, which I fixed by removing the -c

**Comment by GautamShine** [comment]
I was switching from conda to pip for my spaCy install and I noticed that this issue persists for "conda uninstall spacy". In the spacy folder of my site-packages directory, there's some 1.3 GB of files remaining after the uninstall command.
