### ISSUE TITLE
Segmentation fault running tests on Ubuntu 14.04

### ISSUE THREAD

**Issue by hilem** [honnibal/spaCy#71]
This isn't just from running tests. Parsing anything seems to do it, its just the easiest way I've found to reproduce it. Following your build from source steps [here](https://honnibal.github.io/spaCy/quickstart.html#install). Doesn't seem to matter if using system install or using your bootstrap script. Also, needed to install the following packages to get it to compile properly...
`sudo apt-get install libbz2-dev zlib1g-dev libssl-dev`

Output:
```
(.env)root@pos:~/spaCy# py.test tests/
==================== test session starts ====================
platform linux2 -- Python 2.7.5 -- py-1.4.30 -- pytest-2.7.2
rootdir: /root/spaCy, inifile:
collected 142 items

tests/test_docs.py Segmentation fault (core dumped)
(.env)root@pos:~/spaCy#
```

Let me know if any other info would be helpful or anything else I can try. I'd love to test this further but so far I've only been able to reliably get it running locally on OSX. I've run into the same issues on Docker installs as well.

Further Info:

```
(.env)root@pos:~/spaCy# pip2.7 list
cymem (1.11)
Cython (0.22.1)
ecdsa (0.13)
Fabric (1.10.2)
fabtools (0.19.0)
murmurhash (0.24)
numpy (1.9.2)
paramiko (1.15.2)
pathlib (1.0.1)
pip (1.5.6)
plac (0.9.1)
preshed (0.37)
py (1.4.30)
pycrypto (2.6.1)
pytest (2.7.2)
setuptools (3.6)
six (1.9.0)
thinc (3.0)
ujson (1.33)
Unidecode (0.04.18)
wget (2.2)
wsgiref (0.1.2)
```

Also, build-essential and python-dev are installed.

**Comment by honnibal** [comment]
Hey,

I shouldn't have pushed this version to master --- I'm about to do another release, and the data you're downloading is incompatible with the code in the current master branch. I also don't have a tag for the last version. #walkofshame

Specifically, I've switched the data format in the parsing model, to reduce memory usage. But the version you're using is trying to load a model with the old format, which doesn't work.

Options:

- Checkout b266a63f2cc, reinstall requirements (which should be pinned to the correct version of 'thinc', the model loading code that's causing the problem)
- Install from pip, which has the code compatible with the current model
- Hold off a little bit, and I'll have the new model uploaded (probably 2 or 3 hours).

**Comment by hilem** [comment]
I've tried the pip method as well. Python still crashes while parsing. If running in debug mode it appears to also be a segmentation fault. Possible its two different issues, but the pip version crashing is what caused me to try building from source. I'll try starting with a fresh environment and attempt to recreate in a few hours.

**Comment by honnibal** [comment]
Hmm, okay.

Let me get the release up --- I'm doing it now. Then we can at least debug the latest version.

Thanks for the report.

**Comment by honnibal** [comment]
Okay, v0.87 is on pip.

Everything's working on my server, and on Travis. See how you go.

**Comment by hilem** [comment]
Still having issues from pip with python dying. I'll try building from source a little later. Any suggestions on how I can get you more info to debug?

**Comment by honnibal** [comment]
Hmm.

How much memory is available?

**Comment by hilem** [comment]
2GB. It never uses it all though it gets close before crashing. Do you recommend more?

**Comment by hilem** [comment]
I can try more as well, only reason I thought the 2 was safe was I didn't see swap getting pegged.

**Comment by hilem** [comment]
So I have an update... I got it to work. Though I've changed a few variables here, so I'm not 100% on which was the main issue just yet.

Main Variables Changed:
Ubuntu 14.04  -> Ubuntu 15.04
Python 2.7.x   ->  Python 3.4.3
Memory 2GB  -> 8GB

I'm guessing it was the memory seems to be using around 4.2GB of the 8. I'll try a few more scenarios. Hoping it'll play nice w/ 4GB as the 8GB instances are a good deal more $.

**Comment by viksit** [comment]
I had a similar memory issue on a smaller machine. If you're using Amazon -
m4.large might be your friend for better performance.

**Comment by honnibal** [comment]
Depending on what you're doing, you could save some memory by passing load_vectors=False when you create an instance of the English class.

v0.87 has some improvements in memory efficiency — it should use 30-40% less than v0.86.

**Comment by hilem** [comment]
Interesting... I'll give that a try as well. Thanks!
