### ISSUE TITLE
Data download is running really slow

### ISSUE THREAD

**Issue by viksit** [honnibal/spaCy#72]
On executing `python -m spacy.en.download all`, the latency on the data transfer is super high. Has anyone else face this issue? My web connection from other places seems to be okay.

**Comment by honnibal** [comment]
It's hosted off S3 us-west-1. Anyone know if I might be doing anything wrong?

**Comment by viksit** [comment]
I just tried it from an amazon instance. It looks like it might actually BE s3 latency. It was super slow from there too. I guess there's not much to do from your side perhaps. Will leave this open for now and check again in a day or two.

Is it slow for you btw, @honnibal ?

**Comment by honnibal** [comment]
I think the internet was just plain broken yesterday. Massive outage.

**Comment by viksit** [comment]
Closing this out. Apparently there was an outage in the west coast yesterday (wow!).

**Comment by juanshishido** [comment]
@honnibal: Trying `python -m spacy.en.download` and downloading at 0.02 MB/s. I've been trying since last night.

A speed test just I ran shows 53.97 Mbps down.

**Comment by just-dantastic** [comment]
Using python -m spacy.en.download and downloading at 0.05 MB/s.

iperf3 reporting ~11.5 Mbytes transfer. 

Should reopen thread.

**Comment by jason-feng** [comment]
I'm getting the same thing on python3, getting 0.06MB/s
