### ISSUE TITLE
how to access the attributes api?

### ISSUE THREAD

**Issue by simonwiles** [honnibal/spaCy#76]
Hi -- sorry if I've missed something, but I've just installed spaCy (0.88) and immediately hit a problem using the sample code:

    Python 3.4.0 (default, Jun 19 2015, 14:20:21)  
    [GCC 4.8.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from spacy.en import English
    >>> nlp = English()
    >>>
    >>> tokens = nlp(u'I ate the pizza with anchovies.')
    >>> tokens[0].isalpha
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'spacy.tokens.Token' object has no attribute 'isalpha'
    >>>
    >>> lexeme = nlp.vocab[u'Apple']
    >>> lexeme.is_alpha
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'spacy.lexeme.Lexeme' object has no attribute 'is_alpha'

Are the docs behind the most recent release?  Have I missed something obvious?

**Comment by honnibal** [comment]
Hi,

Sorry about this — the docs on the Quick Start page are actually slightly ahead of the current release, which has been delayed a little bit. I shouldn't have pushed that version of the page.

The docs here: http://spacy.io/reference/index.html should be more accurate, but could still contain some inaccuracies.

Development's moving very quickly at the moment, and I'm trying to get the docs rewritten at the same time. Things should be more stable in a week or two.

**Comment by simonwiles** [comment]
no problem -- thanks for the prompt response, and for all your work; this is very impressive.

**Comment by honnibal** [comment]
Fixed in v0.89
