### ISSUE TITLE
Test drive the new site  please :)

### ISSUE THREAD

**Issue by honnibal** [honnibal/spaCy#83]
http://5.9.60.203/

The online demo is off temporarily. But otherwise, please look around and let me know what you think.

**Comment by lechatpito** [comment]
It seems to be offline

**Comment by honnibal** [comment]
Fixed, thanks.

**Comment by geovedi** [comment]
on `put_spans_around_tokens()` example, the line `string = string.replace('\t', '    '` is missing the `)`

**Comment by pquentin** [comment]
displaCy is awesome! Thanks for this. Even if the demo wasn't awesome you should have put it before "Usage by Example" and "Comparisons and Benchmarks". After reading the nice introduction, there's no clear call-to-action: putting the online demo first would help a bit.

**Comment by honnibal** [comment]
Thanks for the suggestion — I've moved it around.

I really hope to get the other language moving soon. It's taken a long time because I'm very committed to quality. When I add something I want to be able to say, "you can build something real with this". That's a lot harder for languages I don't speak, so I've focussed on making English rock solid first.

**Comment by pquentin** [comment]
(Sure, I appreciate it, which is why I'm waiting patiently.)
