### ISSUE TITLE
Advertise Python 2/3 compatibility

### ISSUE THREAD

**Issue by pquentin** [honnibal/spaCy#9]
I had to look to .travis.yml to get that information. It's a great selling point, easy to mention ("NLP with Python 2/3 and Cython") and one of the first things we look at when considering Python libraries. Also, please don't only bury that in the docs. :)

**Comment by honnibal** [comment]
Okay, updated project README.md, and noted non-support of PyPy and Windows while I was at it.

Note that currently all of the auxiliary scripts will fail in Python 3 currently --- although you probably won't need to use them.

I actually didn't think about Python 3 support, or really do anything. That's probably why it didn't really occur to me to advertise it. (You get Python 3 support for free by using Cython, so long as your string-types are correct, which is quite easy when you find the errors at compile-time.)
