### ISSUE TITLE
Installation Instructions unclear

### ISSUE THREAD

**Issue by CpuKnows** [honnibal/spaCy#91]
I installed spacy for anaconda using the instructions on the website:

conda install spacy
$ python -m spacy.en.download

These instructions don't appear to download the expected data.
I stumbled across "python -m spacy.en.download all" and this was the correct proceedure.

Without this the parser and other features don't appear to work with no indication that there is a problem. Please update the documentation.

**Comment by honnibal** [comment]
Fixed! Thanks, sorry about that.
