### ISSUE TITLE
Doc.noun_chunks documented but DNE

### ISSUE THREAD

**Issue by wohali** [honnibal/spaCy#94]
See http://spacy.io/docs/#api . In v0.89, the Doc class is documented to have a `noun_chunks` generator that returns base noun-phrase `Span` objects. This functionality appears to be unimplemented as tested empirically.

```python
>>> doc = nlp(u'The sentence in this example has three noun chunks.')
>>> doc.noun_chunks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'noun_chunks'
```

I also tried code inspection: a grep on this repo for the phrase noun_chunks turns up zero hits.

**Comment by honnibal** [comment]
Ah, thanks.

This is in a branch, and should have been labelled "Coming soon" in the docs. I'll fix the docs. I expect the next release to finish testing quite soon.

**Comment by honnibal** [comment]
spaCy v0.90 now pushed to PyPi, and features this method.
