### ISSUE TITLE
Using custom word vectors in spaCy

### ISSUE THREAD

**Issue by viksit** [honnibal/spaCy#95]
Hi @honnibal - what would be the best way to load custom word-embeddings into spacy?

Thanks!

**Comment by honnibal** [comment]
Hi,

This is much easier in the next version, which should be out this week --- I'm just finishing testing it. For now:

* By default spaCy loads a data/vocab/vec.bin file, where the "data" directory is within the spacy.en module directory
* Create the vec.bin file from a bz2 file using spacy.vocab.write_binary_vectors
* Either replace spaCy's vec.bin file, or call nlp.vocab.load_rep_vectors at run-time, with the path to the binary file.

The above is a bit inconvenient at first, but the binary file format is much smaller and faster to load, and the vectors files are fairly big. Note that GloVe distributes in gzip format, not bzip.

I'm planning to switch to the GloVe vectors as a default, as they seem to have become the standard.

Here are two quick sample snippets to do the above tasks in Python. I haven't had time to test these yet.

```python
    import spacy.vocab

    def set_spacy_vectors(nlp, binary_loc, bz2_loc=None):
        if bz2_loc is not None:
            spacy.vocab.write_binary_vectors(bz2_loc, binary_loc)
        write_binary_vectors(bz2_input_loc, binary_loc)

        nlp.vocab.load_rep_vectors(binary_loc)
```

By default spaCy looks for a vec.bin file, located within its data directory. So you could replace that vector file like this:

```python

    from spacy.vocab import write_binary_vectors
    import spacy.en
    
    from os import path

    def main(bz2_loc):
        bin_loc = path.join(path.dirname(spacy.en.__file__), 'data', 'vocab', 'vec.bin')
        write_binary_vectors(bz2_loc, bin_loc)

if __name__ == '__main__':
    plac.call(main)
```

2.

**Comment by viksit** [comment]
Perfect, thank you - there was a thread about this on the gensim github issues incidentally and the approach suggested there is similar :)

Agree that glove vectors are becoming the standard - but my worry is that data load is going to take even longer. I've been thinking about a service that you load purely for vecs - any thoughts?

**Comment by honnibal** [comment]
Yeah, the loading time is a problem. I think it should be possible to load
asynchronously. That'd help a lot.

**Comment by RXminuS** [comment]
But the GloVe vectors are really good, especially if you want to move to a bit more production battle testing. The biggest pre-trained dataset on the GloVe website is much bigger than 2GB actually! Ideally you can ran a separate service/server that acts as a in-memory lookup table for the vectors so you can start it once and link your program to it. Even if this is just an interface so you can implement it yourself however you see if. Preveiously I actually did a bit of experimenting with Redis for this. It's not great if you want to do nearest lookup...but that's not always required actually. Most of the time we just want the cosine distance between two words and that's fast! Good thing is as well that we can leverage it over to AWS and have it re-used by multiple processing nodes using the same lookup table.

**Comment by honnibal** [comment]
Additional documentation in progress here: http://spacy.io/tutorials/load-new-word-vectors/

The biggest data is 2gb there, as far as I can see? I'm counting this as the compressed size --- the raw text size is irrelevant.

Actually there's very very little advantage to having so many additional words in the vectors file, because of Zipf's law. If you check your data's coverage, I think you'll find you have <1% of your tokens outside of the first 200,000 entries in the vector file, but within the expanded set. Almost the only use I can think of the larger vocabulary is for spelling correction. So it'd be nice to load that into spaCy, as an orth-to-orth mapping, where the vectors are close ad the edit distance is low.

**Comment by viksit** [comment]
@honnibal As per https://spacy.io/tutorials/load-new-word-vectors, did you mean that any text file that contains the format you specify in that blog post, and bz2'd up, should work with 

```
nlp.vocab.load_vectors("file.txt.bz2")
```

as long as this file is copied to the `site-packages/spacy/data/en-1.0.9/vocab/` directory?

I just tried this with the following steps,

- Take the glove file
- Bz2 compress it
- Copy to that directory
- Run `nlp = English()` and `nlp.vocab.load_vectors("filename")`
- 0 dimensions loaded

Any insights?

**Comment by henningpeters** [comment]
Almost, you missed the step _Replacing vec.bin_ in the tutorial. Please read it again. The tutorial says that the function `spacy.vocab.write_binary_vectors` takes a text file with a certain layout (one line per vector, space-delimited token + list of floats) and generates a spaCy-compatible binary vector file. _This vector_ can then be loaded with `nlp.vocab.load_vectors`.

Luckily we just created GloVe vectors (not officially announced yet). This requires latest spaCy version `0.100.6`. Just run:
```
$ sputnik --name spacy install en_glove_cc_300_1m_vectors
```
This downloads and installs following GloVe vectors: Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download). The only change we did was pruning the vocab to 1M entries.
```
You can then load them in spaCy using:
```
en = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
```

**Comment by xumx** [comment]
I'm not sure that I follow the steps to load glove vector. 

```
import spacy
from spacy.en import English

spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
nlp = English()
```

This doesn't seem to replace the vectors. 

Sorry for the basic question

**Comment by henningpeters** [comment]
@xumx you are creating two `English` instances (one with glove vectors, one without) and only use the latter one. What you might have missed is that `spacy.load('en')` is an alternative to `English()`, hence please use just:

```
nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
```

**Comment by michaelcapizzi** [comment]
@henningpeters Thanks for the clarification to @xumx question.  And I'll follow up with some of the things I've learned messing with version `0.101.0`.

The tutorial [here](https://spacy.io/docs/tutorials/load-new-word-vectors) indicates that you would load the `.bz2` using `load_vectors`.  When I do that, however, I have the same problem that @xumx had (showing `0` dimensions).

So I looked at the [source code](https://github.com/spacy-io/spaCy/blob/master/spacy/vocab.pyx), and it looks like there are *two* `load` methods, one of which is `load_vectors_from_bin_loc` which takes a `.bin` file.

And having written a `.bin` file as @henningpeters described above, this worked successfully....with one little bug:
```
>>>giga = nlp.vocab.load_vectors_from_bin_loc("path/to/file.bin")
>>>giga
117
```

The vectors are 300-dimensions, and yet when I test the shape of a vector, it appears to be of the correct size:
```
>>>t = Token()
>>>t.vector.shape
(300,)
```

And thanks @honnibal et. al for adding this functionality to an already awesome package.

**Comment by gitwhistle** [comment]
@honnibal To avoid the issues in https://github.com/spacy-io/spaCy/issues/485,  I was able to download / install via sputnik the language and glove vectors using the following:

`
sputnik --name spacy --repository-url http://index.spacy.io install en
`
`
sputnik --name spacy --repository-url http://index.spacy.io install en_glove_cc_300_1m_vectors
`

Then, I should be able to do this

`
nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
`

But I get this exception:

```
>>> nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 16, in load
    vectors_package = get_package_by_name(vectors, via=via)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 41, in get_package_by_name
    lang = get_lang_class(name)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 28, in get_lang_class
    raise RuntimeError('Language not supported: %s' % lang)
RuntimeError: Language not supported: en_glove_cc_300_1m_vectors
```

Since the sputnik install worked I didn't think I would need to manipulate the `vec.bin` file directly.  Any ideas what might be going wrong?

**Comment by honnibal** [comment]
Hmm. Maybe I packaged this wrong? Not sure. Will look into this.

**Comment by viksit** [comment]
@honnibal any luck? seems to be an issue here.

**Comment by fmailhot** [comment]
The LANGUAGES dict in that module appears to be empty, or not set properly
in set_lang_class

**Comment by honnibal** [comment]
Seems to me that the server stuff has been a red herring here, and this was broken by a code change in 1.1.0.

Until the next release, we can hack around it by simply adding something --- anything --- to the `LANGUAGES` dict with that key. Like so:

```python
import spacy

spacy.set_lang_class('en_glove_cc_300_1m_vectors', 'vectors')
```

**Comment by jcomfort4** [comment]
@honnibal What alternative word vectors are available? I have used the following default vectors

```python
nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')
```

but I would like to test out a 50d or 100d word vector.  I know that I could download a word vector from [GloVe](https://nlp.stanford.edu/projects/glove/) but I was wondering where I could see other word vectors that come with spacy
