### ISSUE TITLE
Move docs under source control?

### ISSUE THREAD

**Issue by bittlingmayer** [honnibal/spaCy#96]
It would be ideal if we could contribute to maintaining the docs.

eg http://spacy.io/docs/ contains the following code:

```
from spacy.en import English
nlp = English(parser=False)
tokens = nlp('Some\nspaces  and\ttab characters')
print([t.orth_ for t in tokens])
```
It should be
```
from spacy.en import English
nlp = English()
tokens = nlp(u'Some\nspaces  and\ttab characters')
print([t.orth_ for t in tokens])
```

**Comment by bittlingmayer** [comment]
I suppose that second issue is related to missing `from __future__ import unicode_literals`

**Comment by honnibal** [comment]
Done --- see spaCy/website .

The docs are written in Jade, and there's some missing documentation about how the site is built. This will be improved soon.
