### ISSUE TITLE
Strange exception if  "python -m spacy.en.download all" is not executed

### ISSUE THREAD

**Issue by redst4r** [honnibal/spaCy#97]
Hi,

I just came across a small "bug" using spacy:
I installed using anancona (conda install spacy), but was unaware of the "python -m spacy.en.download all" that has to be executed as well.

Still, spacy loaded without any errors and I managed to get some examples running.
However, whenever "X.repvec" would be accessed, it crashed with a rather mysterious error:
```python
import spacy.en
nlp = spacy.en.English()
tokens = nlp('some text')
tokens[0].repvec
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-57eacef2446a> in <module>()
----> 1  tokens[0].repvec

spacy/tokens/token.pyx in spacy.tokens.token.Token.repvec.__get__ (spacy/tokens/token.cpp:4472)()

~/anaconda3/envs/NLP/lib/python3.4/site-packages/spacy/tokens/token.cpython-34m.so in View.MemoryView.array_cwrapper (spacy/tokens/token.cpp:12417)()

~/anaconda3/envs/NLP/lib/python3.4/site-packages/spacy/tokens/token.cpython-34m.so in View.MemoryView.array.__cinit__ (spacy/tokens/token.cpp:11342)()

ValueError: Invalid shape in axis 0: 0.
```
Turns out this is because I forgot to run the "python -m spacy.en.download all" command (it took me a while to figure this out, thought there was some problem with my python installation).

Could you catch this exception somehow and indicate to the user that this "download all" command has to be run. This would make life a bit easier for folks like me that just hack in a "conda install ..." without reading the installation instructions :)

btw, great package!

**Comment by syllog1sm** [comment]
Yep, this should happen. There are a few such silent failures if the data isn't downloaded, which is undesirable.

How do you find the documentation, on first impression?

**Comment by redst4r** [comment]
About the documentation: In the beginning I struggled a bit (never done NLP before so some terminology was new to me), especially I was a bit difficult to understandthe interplay/relation of the different classes (Lexemme, Vocab etc). 
However, reading the tutorials I managed to figure out the stuff I needed (some simple filtering based on wordtype, frequency, getting the "base" of the word)!
